### ISSUE TITLE
Document provider creation process

### ISSUE THREAD

**Issue by djrenren** [OneGet/oneget#100]
I've noticed that there's a lot of "community knowledge" on building package providers but there's very little in the way of documentation. It's very clear, for example, what functions need to be implemented to constitute a provider, but it is super unclear how to actually build something and get oneget to recognize it. Basically, a "start from zero" guide on building package providers and plugins seems necessary.

**Comment by dfinke** [comment]
Good point. I was thinking of taking a stab at getting started doc. What "kind of" provider were you thinking of building?

**Comment by djrenren** [comment]
I was going to build one basically analagous to aptitude in terms of pulling down zips that are unzipped relative to the fs root. But that's pretty complicated. As long as I know how to build and get one get to recognize my provider I'd be set

**Comment by fearthecowboy** [comment]
I realize that it's not exactly heavily documented at this point; I'm trying to squeeze some time in to address this.

FYI, this is what you get when you don't have to wait until the product is finished and shipped to start playing with it. In the old "Microsoft" we'd do all the dev work before you'd even see anything, and if something was not-very-well-thought-thru, well... it'd be too late to change it. At least this way we can (and already have) changed directions and implementation based on feedback.

Anyway, the current state-of-the-project is to fork the ProviderSDK project and start filling in the blanks. Gimme a couple hours, and I'll make sure that it works right. 

Ideally, working with the ProviderSDK sample, you should be able to compile it, and drop the resultant binary into the `"$env:localappdata\oneget\providerassemblies"` or `"$env:programfiles\oneget\providerassemblies"` directory and fire up powershell and it should find it. 

I'll also enlist our PM, Xumin to spend some time putting together a step-by-step example

**Comment by fearthecowboy** [comment]
Quick and dirty instructions:

- Requires: 


- fork the project at https://github.com/OneGet/ProviderSdk to your own account
- rename the project to something useful
- clone your project to your local machine
- edit the packageprovider.c# script and change the name in the source (ie https://github.com/OneGet/ProviderSdk/blob/master/PackageProvider.cs#L64 )
- you should also change the project output name in the `.csproj` to something other than `"SampleProvider.dll" `
- and update the install-provider.ps1 script with the correct output name. 

Once you build the provider script

**Comment by fearthecowboy** [comment]
Quick and dirty instructions:

###  Requires: 
    - vs 2013 
    - YOU MUST BE RUNNING THE Experimental build of ONEGET : http://oneget.org/install-oneget.exe 

### procedure
- fork the project at https://github.com/OneGet/ProviderSdk to your own account
- rename the project to something useful
- clone your project to your local machine
- edit the packageprovider.c# script and change the name in the source (ie https://github.com/OneGet/ProviderSdk/blob/master/PackageProvider.cs#L64 )
- you should also change the project output name in the `.csproj` to something other than `"SampleProvider.dll" `
- and update the install-provider.ps1 script with the correct output name. 

Once you build the provider script, run the install-provider.ps1 script and it will copy the assembly to the right spot.

Then:

``` powershell

# need to run the community build.
> ipmo oneget-edge 

# see if it loaded your provider assembly:
> get-packageprovider 

PS C:\root\oneget\output\v45\Debug\bin> get-packageprovider
WARNING: MSG:ProviderSwidtagUnavailable

Name                     Version          DynamicOptions
----                     -------          --------------
YourProvider           1.0.0.0          {}

```

**Comment by djrenren** [comment]
Thank you so much! That was the missing link I needed. If you have the time I'd love to see this shoved in the docs somewhere for the benefit of others (if it's not already). But personally, I'm all set. Thank you!!
