### ISSUE TITLE
OneGet/WMF 5.0 November 2014 update seems to have broken WMI and CIM

### ISSUE THREAD

**Issue by Chromebuster** [OneGet/oneget#102]
This is a rather interesting issue. I'll attach a PowerShell Transcript to show what often happens anymore when trying to do anything involving WMI queries. It didn't start happening until I installed OneGet and the rest of the Windows Management Framework 5.0.
PowerShell Transcript follows:
**********************
Windows PowerShell transcript start
Start time: 20150202155046
Username: CORP\Katherine.Moss
RunAs User: CORP\Katherine.Moss
Machine: HESIUS (Microsoft Windows NT 6.3.9600.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Process ID: 1114924
**********************
Transcript started, output file is C:\Users\katherine.moss\Documents\PowerShell_transcript.HESIUS.qR3V7bPH.201502021550
46.txt

PS C:\Windows\system32> get-netadapter

PS C:\Windows\system32> TerminatingError(Get-NetAdapter): "Cannot connect to CIM server. Invalid namespace "
get-netadapter : Cannot connect to CIM server. Invalid namespace
At line:1 char:1
+ get-netadapter
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (MSFT_NetAdapter:String) [Get-NetAdapter], CimJobException
    + FullyQualifiedErrorId : CimJob_BrokenCimSession,Get-NetAdapter

PS C:\Windows\system32> get-netipaddress

PS C:\Windows\system32> TerminatingError(Get-NetIPAddress): "Cannot connect to CIM server. Invalid namespace "
get-netipaddress : Cannot connect to CIM server. Invalid namespace
At line:1 char:1
+ get-netipaddress
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (MSFT_NetIPAddress:String) [Get-NetIPAddress], CimJobException
    + FullyQualifiedErrorId : CimJob_BrokenCimSession,Get-NetIPAddress

PS C:\Windows\system32> choco update skype
Updating skype from 6.22.81.105 to 7.1.0.105
Chocolatey (v0.9.8.31) is installing 'skype' and dependencies. By installing you accept the license for 'skype' and each
 dependency you are installing.

skype v7.1.0.105
Get-WmiObject : Invalid namespace "root\cimv2"
At C:\ProgramData\chocolatey\lib\skype.7.1.0.105\tools\chocolateyInstall.ps1:7 char:10
+   return Get-WmiObject -Class Win32_Product | Where-Object {$_.Name - ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCommand

Installing skype...
Write-Error : [ERROR] Running msiexec with /i "C:\Users\KATHER~1.MOS\AppData\Local\Temp\chocolatey\skype\skypeInstall.m
si" /qn /norestart STARTSKYPE=FALSE TRANSFORMS=:RemoveDesktopShortcut.mst TRANSFORMS=:RemoveStartup.mst  was not succes
sful. Exit code was '1638'.
At C:\ProgramData\chocolatey\chocolateyinstall\helpers\functions\Start-ChocolateyProcessAsAdmin.ps1:46 char:5
+     Write-Error $errorMessage
+     ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Error

Write-Error : skype did not finish successfully. Boo to the chocolatey gods!
-----------------------
[ERROR] [ERROR] Running msiexec with /i "C:\Users\KATHER~1.MOS\AppData\Local\Temp\chocolatey\skype\skypeInstall.msi" /q
n /norestart STARTSKYPE=FALSE TRANSFORMS=:RemoveDesktopShortcut.mst TRANSFORMS=:RemoveStartup.mst  was not successful.
Exit code was '1638'.
-----------------------
At C:\ProgramData\chocolatey\chocolateyinstall\helpers\functions\Write-ChocolateyFailure.ps1:30 char:3
+   Write-Error $errorMessage
+   ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Error

Write-Error : skype did not finish successfully. Boo to the chocolatey gods!
-----------------------
[ERROR] [ERROR] Running msiexec with /i "C:\Users\KATHER~1.MOS\AppData\Local\Temp\chocolatey\skype\skypeInstall.msi" /q
n /norestart STARTSKYPE=FALSE TRANSFORMS=:RemoveDesktopShortcut.mst TRANSFORMS=:RemoveStartup.mst  was not successful.
Exit code was '1638'.
-----------------------
At C:\ProgramData\chocolatey\chocolateyinstall\helpers\functions\Write-ChocolateyFailure.ps1:30 char:3
+   Write-Error $errorMessage
+   ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Error

Write-Error : Package 'skype v7.1.0.105' did not install successfully: [ERROR] Running msiexec with /i "C:\Users\KATHER
~1.MOS\AppData\Local\Temp\chocolatey\skype\skypeInstall.msi" /qn /norestart STARTSKYPE=FALSE TRANSFORMS=:RemoveDesktopS
hortcut.mst TRANSFORMS=:RemoveStartup.mst  was not successful. Exit code was '1638'.
At C:\ProgramData\chocolatey\chocolateyinstall\functions\Chocolatey-NuGet.ps1:90 char:17
+ ...             Write-Error "Package `'$installedPackageName v$installedP ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Error

Finished installing 'skype' and dependencies - if errors not shown in console, none detected. Check log for errors if un
sure.

PS C:\Windows\system32> exit
**********************
Windows PowerShell transcript end
End time: 20150202160759
**********************

**Comment by fearthecowboy** [comment]
Hmm. 

Well, It's possible that WMI got broke from the WMF 5; I'd recommend that you file a connect bug at https://connect.microsoft.com/PowerShell

The part where you call ` choco update skype` it looks like you're using the official version of chocolatey (not made by MS) and not the one that works thru OneGet.

It does look like the broken WMI is affecting Windows Installer, which is why chocolatey looks broken too.

**Comment by Chromebuster** [comment]
Okay, thanks. What exactly should I tell them? I’d like to preferably fix this without rebuilding my system; all of my resources are down for the moment.

**Comment by fearthecowboy** [comment]
Just post a bug that shows: 

``` text
This is a rather interesting issue. I'll attach a PowerShell Transcript to show what often happens anymore when trying to do anything involving WMI queries. It didn't start happening until I installed the Windows Management Framework 5.0.
PowerShell Transcript follows:

Windows PowerShell transcript start
Start time: 20150202155046
Username: CORP\Katherine.Moss
RunAs User: CORP\Katherine.Moss
Machine: HESIUS (Microsoft Windows NT 6.3.9600.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Process ID: 1114924

Transcript started, output file is C:\Users\katherine.moss\Documents\PowerShell_transcript.HESIUS.qR3V7bPH.201502021550
46.txt

PS C:\Windows\system32> get-netadapter

PS C:\Windows\system32> TerminatingError(Get-NetAdapter): "Cannot connect to CIM server. Invalid namespace "
get-netadapter : Cannot connect to CIM server. Invalid namespace
At line:1 char:1

get-netadapter
~~~~~~~~~~~~~~
CategoryInfo : ResourceUnavailable: (MSFT_NetAdapter:String) [Get-NetAdapter], CimJobException
FullyQualifiedErrorId : CimJob_BrokenCimSession,Get-NetAdapter
PS C:\Windows\system32> get-netipaddress

PS C:\Windows\system32> TerminatingError(Get-NetIPAddress): "Cannot connect to CIM server. Invalid namespace "
get-netipaddress : Cannot connect to CIM server. Invalid namespace
At line:1 char:1

get-netipaddress
~~~~~~~~~~~~~~~~
CategoryInfo : ResourceUnavailable: (MSFT_NetIPAddress:String) [Get-NetIPAddress], CimJobException
FullyQualifiedErrorId : CimJob_BrokenCimSession,Get-NetIPAddress
```


If you uninstall the WMF 5 and reboot, does that fix the problem?

**Comment by Chromebuster** [comment]
Great. Thanks. Sorry for the confusion. At the moment though, I’ve got to figure out how to navigate that site with a screen reader. The layout’s terrible.
