### ISSUE TITLE
Relation between Boxstarter and OneGet, if any?

### ISSUE THREAD

**Issue by AnneTheAgile** [OneGet/oneget#106]
hi! I am so excited about oneget's 'apt-get' for windows and read also about boxstarter [2,3]. Is there any current or planned integration with boxstarter? 
AnneTheAgile
Refs; 
1.[]Ticket #30 option not to confirm each install, by user of boxstarter
2.[]Boxstarter leverages Chocolatey packages to automate the installation of software and create repeatable, scripted Windows environments.; BUG only support is ggl group must signin and be member ugh;  DEV MACHINE LIKE ANSIBLE but Posh chocolatey!!; X.Boxstarter ;; http://boxstarter.org/InstallBoxstarter
3.[] ; X.Scott Hanselman's 2014 Ultimate Developer and Power Users Tool List for Windows - Scott Hanselman ;; http://www.hanselman.com/blog/ScottHanselmans2014UltimateDeveloperAndPowerUsersToolListForWindows.aspx

**Comment by ddimtirov** [comment]
It would have been nice to actually answer the question before closing it...

**Comment by jianyunt** [comment]
Good point.  Reopen it now and will bring it up to our meeting.

**Comment by xumins** [comment]
BoxStarter.org is a UI web tool that is based on Chocolatey. There is no relationship between BoxStarter and OneGet. There is an ongoing effort to have a OneGet provider for chocolatey, by the community at https://github.com/chocolatey/chocolatey-oneget, which will enable PowerShell experience of using OneGet cmdlets to install chocolatey packages. Even with that, there will not have direct link between BoxStarter and OneGet.
