### ISSUE TITLE
Allow specifying of install location for PSGet

### ISSUE THREAD

**Issue by djrenren** [OneGet/oneget#107]
Is there a way to specify where to install a module when using the psget provider. It basically copies directly into the C:\Program Files\WindowsPowershell\Modules folder anyway. I'd like to install to my user directory so that admin permissions aren't required.

**Comment by gwojan** [comment]
++1, :D

I tend to create a separate directory that gets added to $ENV:PSModulesPath and all my modules go in there.

**Comment by Jaykul** [comment]
If you mean the PowerShellGet provider, then specify -Scope CurrentUser

You can't install to random directories though, just the Program Files\WindowsPowerShell\Modules location or your user Documents\WindowsPowerShell\Modules folder.

**Comment by gwojan** [comment]
Thanks Joel. I've used the -Scope parameter but I really do need the ability to specify an alternate directory from time to time. I'm trying to be more standardized on where things get installed but the environment I work in requires the ability to override the default install location.

**Comment by jianyunt** [comment]
You can use save-module to different path.
