### ISSUE TITLE
Specifying ProviderName on Install-Package hangs

### ISSUE THREAD

**Issue by dfinke** [OneGet/oneget#108]
I'm running the Feb preview on Win 8.1 Enterprise.

I added  `-ProviderName nuget` to get tabcompletion for the dynamic params on the `Install-Package`. 

`find-package elasticsearch -ProviderName nuget  | Install-Package -Verbose -ProviderName nuget  -Destination C:\pkg`

It hangs.

I remove the `-ProviderName` and it works.

**Comment by fearthecowboy** [comment]
How very uncool!

I'll look into it.

**Comment by quoctruong** [comment]
This seems to be fixed.
