### ISSUE TITLE
Oneget Cancels Install Request on slower systems 

### ISSUE THREAD

**Issue by WetHat** [OneGet/oneget#109]
I tried to install Java through the Chocolatey provider in OneGet like so:
    PS> install-package javaruntime-platformspecific

On slower hardware that yields:

_WARNING: Provider 'Chocolatey' is not respecting the responsiveness threshold in a timely fashion; Canceling request._

The reason actually is that the ChocolateyInstall.ps1 tries to determine whether Java is already present by calling:

    PS>  Get-WmiObject -Class Win32_Product | Where-Object {$_.Name -match '^Java \d+ Update \d+'}

On some systems this call takes a very looong time and causes OneGet to give up.

I know that there needs to be some sort of timeout to avoid endless loops. So my suggestion would be to add an optional timeout parameter to the Install-Package cmdlet. E.G

    PS> Install-package javaruntime-platformspecific -timeout 100

another idea would be to determine the system speed and adjust the timeout automatically. Perhaps a good timeout would be twice the time it takes to run Get-WmiObject -Class Win32_Product 

So long,

WetHat

**Comment by gwojan** [comment]
Actually, not using Win32_Product to determine if software is already installed is probably a much better idea, IMHO...

I've run into this problem with Chocolatey and have requested that package maintainers use Win32_Product. It has too many side effects, very poor performance and misses packages not installed via MSI.

**Comment by WetHat** [comment]
I suppose you meant to say ' ...that package maintainers **not** use Win32_Product'. I understand your point though. I must admit that I've been using
    Get-WmiObject -Class Win32_Product
for **uninstallation** quite a bit, because it is as simple as calling $prod.Uninstall() on the product you want to uninstall.

**Comment by fearthecowboy** [comment]
Because of the way that OneGet works in parallel when it can, I had to put in some timeout-based cancellation.

Ideally, providers should be periodically checking the cancellation notice (and when they do, that 'refreshes' their timeout.

I think I'm going to turn off the auto-cancellation until we get a lot more providers working with it correctly.
