### ISSUE TITLE
Untrusted Package Source

### ISSUE THREAD

**Issue by iainbrighton** [OneGet/oneget#114]
OK - so I've almost finished putting together a Microsoft App-V OneGet provider. However, when installing a package from a "trusted" package source, it says it's not a trusted location?!

![image](https://cloud.githubusercontent.com/assets/7023258/6599524/38a5c63c-c802-11e4-92f3-a580ccc759c9.png)

I have obviously missed something somewhere! Any ideas? I'm using a Powershell module to implement this if it makes any difference?

Thanks, Iain

**Comment by fearthecowboy** [comment]
Wow! Awesome!

When you construct a SoftwareIdentity, in the details hashtable, put a key/value pair of "IsFromTrustedSource" , "True"

**Comment by iainbrighton** [comment]
Got it - there's a FromTrustedSource switch parameter on the New-SoftwareIdentity function!

Another quick query - what's the purpose of the IsValidated property on a package source? What is required of a OneGet provider here?

Thanks, Iain

**Comment by fearthecowboy** [comment]
OneGet permits a package provider to accept arbitrary values for sources- sometimes the provider can't know for certain that the source is legal, so this lets you mark a source as "looks like it, but I haven't checked"

Example:

``` powershelll

register-packagesource -provider nuget -name foo -location http://foo.com -SkipValidate

Name                             ProviderName     IsTrusted  IsRegistered IsValidated  Location
----                             ------------     ---------  ------------ -----------  --------
foo                              NuGet            False      True         False        http://foo.com

```

If the location that's passed in *could* be a source, but the cost to validating that there is an actual responding end point is high, and the user just wants to force it, you can say "yeah, that's registered, but we're not sure if it's actually a source.

**Comment by iainbrighton** [comment]
Got it - so the provider ___should___ be validating the location unless otherwise specified. If it's invalid we should be throwing an error?
