### ISSUE TITLE
Dynamic Install Parameters

### ISSUE THREAD

**Issue by iainbrighton** [OneGet/oneget#115]
Me again! How does one utilise dynamic parameters when installing packages? I've configured the dynamic parameters for the install category as follows:

```
function Get-DynamicOptions {
    param(
        [Microsoft.OneGet.MetaProvider.PowerShell.OptionCategory] $category
    )
    Write-Debug ('In {0} Provider - ''Get-DynamicOption'' for category ''{1}''.' -f $providerName, $category);
	switch ($category) {
	    Package {
			# options when the user is trying to specify a package 
		}
		Source {
			#options when the user is trying to specify a source
		}    
		Install {
			#options for installation/uninstallation
            Write-Output (New-DynamicOption $category Global Switch $false);
            Write-Output (New-DynamicOption $category Mount Switch $false);
		}
	}
}
```
They show up when running Install-Package (with tab completion!). However, I can't seem to detect these within the Install-Package function of the provider. Here's what I've got:
```
function Install-Package { 
    param(
        [Parameter()] [System.String] $fastPackageReference,
        [Parameter()] [Switch] $Global,
        [Parameter()] [Switch] $Mount
    )
    Write-Debug ('In {0} Provider - ''Install-Package'' - Reference ''{1}''.' -f $providerName, $fastPackageReference);
    Write-Debug ('In {0} Provider - ''Install-Package'' - IsGlobal ''{1}''.' -f $providerName, $Global);
    Write-Debug ('In {0} Provider - ''Install-Package'' - IsMount ''{1}''.' -f $providerName, $Mount);
....
}
```
This is the outcome.
![image](https://cloud.githubusercontent.com/assets/7023258/6602177/f5c810c6-c811-11e4-85f6-87bb1bfdefba.png)

I am no doubt (again) doing something wrong. Any help is appreciated and I appreciate that this isn't really an "issue". If I should be posting this elsewhere please let me know, Iain

**Comment by fearthecowboy** [comment]
You get dynamic options via the `$request` object.

``` powershell
      #inside your install-package function
      $options = $request.Options

      #dump out all the options to the verbose channel
      if($options) {
            foreach( $o in $options.Keys ) {
                Write-Verbose ("OPTION: {0} => {1}" -f ($o, $request.Options[$o]) )
            }
       }
```

IIRC, it's a `Dictionary<string,string>` collection. I think

**Comment by fearthecowboy** [comment]
FYI, the reason that it's done this way, is that there is a huge amount of variablility in what providers do and accept, so only the very basic, mandatory parameters pass via function parameters, and virtually everything else is accessed via $request.

This also has the optimization that that data that a given provider doesn't use, *never* gets marshalled across. (while no big deal now, if we make it so that providers can be out-of-process sometime later, this will be huge.)

**Comment by iainbrighton** [comment]
Excellent - I shall implement!

The documentation is a little sparse which is to be expected at this point in the project. Would you like me to update the PS template with more verbose documentation from the lessons I've learnt? It'll save you having to answer these questions again in future :).

If so, how would you like me to do this? Pull request?

**Comment by fearthecowboy** [comment]
That would be great!


Yeah, I know the docs are thin; believe it or not, that's a good thing.

That happens when you don't have to wait till the product is finished before getting to play with it :)

Pull requests joyfully accepted.
