### ISSUE TITLE
Install-package defaults to "Yes" for non-trusted sources?

### ISSUE THREAD

**Issue by jefmes** [OneGet/oneget#116]
I'm experimenting with OneGet for the first time tonight, and I love what I'm seeing so far.  I was running through a few scenarios, and this jumped out at me (indirectly.) I apologize if this has been addressed elsewhere, but my searches came up empty.

--------------------------------------------------------------
PS C:\Windows\system32> install-package 7zip

The package '7zip' comes from a package source that is not marked as trusted.
Are you sure you want to install software from 'chocolatey'?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):

The package '7-Zip 9.22 (x64 edition)' comes from a package source that is not marked as trusted.
Are you sure you want to install software from 'C:\Users\Jeff\AppData\Local\Temp\chocolatey\7Zip\7Zipinstall.msi'?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):

-------------------------------------------------------------
1. Wouldn't chocolatey be a trusted source?

2. My wife, who is relatively tech saavy but in a consumer mind-set and not an IT or developer perspective, saw the prompts while I was demoing it for her and said, "Shouldn't something like that always default to No? Isn't Yes a bad idea in case you made a mistake?"

There could very well be reasons for it being default Yes but I thought she had a good point - I noticed it too, but I thought it was telling that she also mentioned it. What do you think?

**Comment by jianyunt** [comment]
The default is No now in WMF 5.0 Product Preview.
