### ISSUE TITLE
Installer wiping psmodulepath

### ISSUE THREAD

**Issue by dsolodow** [OneGet/oneget#124]
Windows 8.1 Enterprise x64, WMF 4.0.

The last experimental build or two, after running the install it seems to over-write the PSModulePath both machine-wide and for my user account.

I run the installer as a different user; my main login isn't an admin on the PC.

**Comment by fearthecowboy** [comment]
Hmm. It shouldn't be wiping it, it was supposed to be additive. It's still doing this with the latest builds? *sigh*...

We're building a newer set of official installers that should be a bit smarter, we'll just have to grin and bear it with the experimental ones for a bit longer.
