### ISSUE TITLE
How should providers request elevation?

### ISSUE THREAD

**Issue by madewokherd** [OneGet/oneget#125]
I have installation of python wheel packages working (yay), but for a system-wide python install it only works if you run powershell as administrator (boo).

When my provider detects that an install will fail due to permissions (which might be solved by retrying as administrator), is there a way that I can have it return that information to oneget? If not, how should I request admin privs in this situation?

**Comment by jianyunt** [comment]
can you use request.WriteError() to communicate the message from provider to OneGet.
