### ISSUE TITLE
The property 'PackageManagementProvider' cannot be found on this object

### ISSUE THREAD

**Issue by dsolodow** [OneGet/oneget#129]
OneGet build 1.15.107.31256
Windows 8.1 x64
PowerShell 4.0

When I ran 'update-module' I got several occurrences of this block:
WARNING: The property 'PackageManagementProvider' cannot be found on this object. Verify that the property exists.
WARNING: Cannot index into a null array.
WARNING: Cannot bind argument to parameter 'fastPackageReference' because it is an empty string.

This also triggers on Install-Module from PSGallery

**Comment by gwojan** [comment]
I just found this same issue last night...
