### ISSUE TITLE
Positional parameter cannot be found that accepts argument '<version_number>'

### ISSUE THREAD

**Issue by iainbrighton** [OneGet/oneget#131]
Hi Garrett,

When attempting to update the AppV OneGet provider to support the PackageManagement name change, I'm now receiving an error about the Version returned from Find-Package function. The last thing the function does it write out a package with the New-SoftwareIdentity function. 

Here's a screenshot of the error with the -Debug switch:

![image](https://cloud.githubusercontent.com/assets/7023258/7421460/723b797c-ef7c-11e4-9df6-415993354250.png)

Any ideas what I've missed? We did a rename of all OneGet references to PackageManagement in the .psm1 file. I presume the 'functions.ps1' file is just there for reference and not actually loaded by OneGet?

Thanks again, Iain

**Comment by fearthecowboy** [comment]
Ah, a change got made to Get-InstalledPackages – you have to add three more parameters ( [string] $requiredversion, [string] $minVersion, [string]maxversion)

G

**Comment by iainbrighton** [comment]
Thanks Garrett! Presumably they're passed as named parameters so I don't need to worry about the order they're defined (will check tomorrow anyway!)? Cheers, Iain

**Comment by fearthecowboy** [comment]
Ah, no position is important, not so much parameter Name.

**Comment by iainbrighton** [comment]
Just to clarify, I need:

```[Parameter()] [string] $Name,
[Parameter()] [string] $requiredversion,
[Parameter()] [string] $minVersion,
[Parameter()] [string]maxversion```

On the Get-InstalledPackage function (I currently just have Name)? In that order?

**Comment by fearthecowboy** [comment]
Yes
