### ISSUE TITLE
Solution has wrong GUID during msbuild

### ISSUE THREAD

**Issue by kruug** [OneGet/oneget#135]
Microsoft (R) Build Engine version 4.0.30319.34209
[Microsoft .NET Framework, version 4.0.30319.34209]
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 2015-05-06 3:40:02 PM.
C:\<path to source>\oneget\PackageManagement.sln : Solution file error MSB4051: Project {0298D025-D727-485A-8691-5ECCCA27F424} is referencing a project with GUID {7044B856-6D51-498F-8192-01F219908192}, but a project with this GUID was not found in the .SLN file.

Build FAILED.

  C:\<path to source>\oneget\PackageManagement.sln : Solution file error MSB4051: Project {0298D025-D727-485A-8691-5ECCCA27F424} is referencing a project with GUID {7044B856-6D51-498F-8192-01F219908192}, but a project with this GUID was not found in the .SLN file.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.02

**Comment by jianyunt** [comment]
please try oneget.org for the latest version.

**Comment by kruug** [comment]
So, this repo is dead and OneGet is no longer open source?

**Comment by jianyunt** [comment]
No. This is an active repo.  The latest source can be found here: https://github.com/oneget/oneget.

**Comment by kruug** [comment]
Does that have a fixed GUID?

That was the whole point of this Issue.  A wrong GUID.  Answering that with "New version released" doesn't address this issue if the issue of the wrong GUID isn't fixed.

**Comment by jianyunt** [comment]
are you still seeing the error? we can download and build no errors.

**Comment by kruug** [comment]
I haven't built the newest release, but the release that was there when I opened the issue I was...

**Comment by jianyunt** [comment]
Kruug, please feel free to reactivate it if this is still the issue for you. thx.
