### ISSUE TITLE
PackageManagement-related DSC Resources should be a part of the PackageManagement-module

### ISSUE THREAD

**Issue by janegilring** [OneGet/oneget#145]
Taking the Windows 10 RTM as an example, where two modules containing DSC Resources is manually installed, I have the following modules present under C:\Program Files\WindowsPowerShell\Modules
Mode                LastWriteTime         Length Name                                                         

---

d-----       10.07.2015     13.04                PackageManagement  
d-----       09.08.2015     15.53                PackageManagementProviderResource  
d-----       06.04.2015     15.44                xOneGet                                                      

"The PackageManagementProviderResource (used to be called OneGetProviderResource) module contains the following Windows PowerShell Desired State Configuration (DSC) resources to allow you to manage packages and Windows PowerShell modules."
"The xOneGet modules contains a DSC Resource to install/uninstall packages using PackageManagement."

In my opinion it would be great if the above could be consolidated into the PackageManagement module, as it would be easier to understand for PowerShell users. The current structure with many different modules all related to PackageManagement makes it confusing for new PowerShell users I believe.

In practice, this suggests that all DSC Resources under C:\Program Files\WindowsPowerShell\Modules\PackageManagementProviderResource\DSC Resources and PackageManagementProviderResource\xOneGet\DSC Resources is consolidated into PackageManagement\DSC Resources

**Comment by brywang-msft** [comment]
Merge done in WIP branch. This will also be the case in the next major Windows release.
