### ISSUE TITLE
OneGet bootstraps nuget 2.8.5 provider which fails with loader exceptions on Win10

### ISSUE THREAD

**Issue by heaths** [OneGet/oneget#147]
I'm not sure exactly what is causing this failure, but PackageManagement / OneGet wants to install nuget 2.8.5 (AnyCPU) from a OneGet server and on one of my machines this fails 100% of the time with loader exceptions in the EXE. Even just running `$env:LocalAppData\PackageManagement\ProviderAssemblies\nuget-anycpu.exe` fails with,

    Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more
information.

I tried to replace the executable with 2.8.6 or 3.1.0-beta but it always gets replaced. As such, I'm blocked from installing any PSModule-provided modules like 'MSI' (mine). This machine was upgraded from Win8.1 Pro to Win10 Pro.

This works on another machine, which was a fresh install of Win10 Ent.

Either way, 2.8.6 is the current, stable v2 release. Probably should update the provider package reference. 2.8.6 works just fine on either machine.

**Comment by heaths** [comment]
Debugging the process, the LoaderExceptions (3) are all:

    Could not load file or assembly 'NuGet, Version=2.1.31022.9038, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

The fusion log within the exception shows:

    === Pre-bind state information ===
    LOG: DisplayName = NuGet, Version=2.1.31022.9038, Culture=neutral, PublicKeyToken=null
     (Fully-specified)
    LOG: Appbase = file:///C:/Users/Heath/AppData/Local/PackageManagement/ProviderAssemblies/
    LOG: Initial PrivatePath = NULL
    Calling assembly : SymbolSource.Integration.NuGet.CommandLine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
    ===
    LOG: This bind starts in LoadFrom load context.
    WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
    LOG: No application configuration file found.
    LOG: Using host configuration file: 
    LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
    LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
    LOG: Attempting download of new URL file:///C:/Users/Heath/AppData/Local/PackageManagement/ProviderAssemblies/NuGet.DLL.
    LOG: Attempting download of new URL file:///C:/Users/Heath/AppData/Local/PackageManagement/ProviderAssemblies/NuGet/NuGet.DLL.
    LOG: Attempting download of new URL file:///C:/Users/Heath/AppData/Local/PackageManagement/ProviderAssemblies/NuGet.EXE.
    LOG: Attempting download of new URL file:///C:/Users/Heath/AppData/Local/PackageManagement/ProviderAssemblies/NuGet/NuGet.EXE.
    LOG: Attempting download of new URL file:///C:/Users/Heath/AppData/Local/NuGet/Commands/SymbolSource.Integration.NuGet.CommandLine.1.3.4/NuGet.DLL.
    LOG: Attempting download of new URL file:///C:/Users/Heath/AppData/Local/NuGet/Commands/SymbolSource.Integration.NuGet.CommandLine.1.3.4/NuGet/NuGet.DLL.
    LOG: Attempting download of new URL file:///C:/Users/Heath/AppData/Local/NuGet/Commands/SymbolSource.Integration.NuGet.CommandLine.1.3.4/NuGet.EXE.
    LOG: Attempting download of new URL file:///C:/Users/Heath/AppData/Local/NuGet/Commands/SymbolSource.Integration.NuGet.CommandLine.1.3.4/NuGet/NuGet.EXE.

Seems I installed it a long time ago from Chocolatey and it hasn't been updated. Ignoring extensions might be a good idea when installing modules, but it seems the option can't be parsed from the command line and is only settable programmatically.

**Comment by jianyunt** [comment]
@heaths, we rewrote the nuget provider that runs on nano and full server.The source is  https://github.com/OneGet/NuGetProvider.  It no longer wraps around nuget.exe. Instead only when people run publish-module, PowerShellGet will download the nuget.exe from https://nuget.org/nuget.exe.

On your machine, if you download it from https://nuget.org/nuget.exe, do you still see any problems?

**Comment by heaths** [comment]
If PowerShellGet doesn't find nuget.exe exactly where it expects to find it (i.e. it's not checking my PATH - at least, not as of a couple weeks ago - did you ship new bits since?), it always downloads it. I do keep nuget.exe in my PATH, too (a choco-installed one).

**Comment by quoctruong** [comment]
Hi Heaths,

PowerShellGet looks for nuget.exe in these locations:

1. If you are admin, $env:ProgramData\Microsoft\Windows\PowerShell\PowerShellGet
2. If you are local user, $env:LOCALAPPDATA\Microsoft\Windows\PowerShell\PowerShellGet
3. Otherwise, it will get the location of NuGet.exe if this is available under $env:Path

As for the Path problem, may I ask what do you get when you run the following command?

Get-Command -Name "nuget.exe" `
                                                              -ErrorAction SilentlyContinue `
                                                              -WarningAction SilentlyContinue | 
                            Microsoft.PowerShell.Core\Where-Object { 
                                $_.Path -and 
                                ((Microsoft.PowerShell.Management\Split-Path -Path $_.Path -Leaf) -eq "nuget.exe") -and
                                (-not $_.Path.StartsWith($env:windir, [System.StringComparison]::OrdinalIgnoreCase)) 
                            } | Microsoft.PowerShell.Utility\Select-Object -First 1

**Comment by heaths** [comment]
Unless you've updated it via Windows Update, point 3 (PATH) has never happened. nuget.exe (and, yes, .exe - though it shouldn't really matter for your lookup if it's a .cmd, .bat, or any other PATHEXT) is definitely in my PATH, but PSGet still tries to download it.

**Comment by quoctruong** [comment]
Hi heaths, I believe the latest PowerShellGet will look for NuGet.exe under $env:Path as well. This will be available in soon to be released WMF. Do you mind sharing the PowerShellGet you are using? You can send to my email at quoct@microsoft.com
