### ISSUE TITLE
Find-Module, Publish-Module (?Others) fail if module path contains folder on PSDrive

### ISSUE THREAD

**Issue by ChrisWarwick** [OneGet/oneget#149]
If a folder in $env:psmodulepath is on a PSDrive then Find-Module and Publish-Module (and probably others) hang forever without issuing any error messages.  Suspect there's a problem somewhere in C# with folder/path handling that's assuming native folder paths and not handling PSDrive folders.

Repro:
New-PSDrive -Name psd1: -Root c:\data\powershell -PSProvider FileSystem 
$env:PsModulePath = 'psd1:\modules;'+$env:PsModulePath
Find-Module Anything

..... Hangs

**Comment by Jaykul** [comment]
For those following along at home, this **is** a bug in the PackageManagement module, not PowerShellGet. The command that actually hangs is `Get-PackageProvider`

**Comment by jianyunt** [comment]
which OS are you running?

**Comment by jianyunt** [comment]
Win10?

**Comment by ChrisWarwick** [comment]
Yes, Win10.  Currently on Insider build 10525.  $PsVersionTable:
Name                           Value
----                           -----
PSVersion                      5.0.10525.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.10525.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0.10525.0}
PSRemotingProtocolVersion      2.3

**Comment by jianyunt** [comment]
Thanks for reporting it. I can repro the issue now. The fix will be in the next release.

**Comment by ChrisWarwick** [comment]
Thank You :-)

**Comment by quoctruong** [comment]
Closed as this is fixed in the source code uploaded.
