### ISSUE TITLE
Get-Package cannot return multiple package instances with the same name

### ISSUE THREAD

**Issue by madewokherd** [OneGet/oneget#150]
When a provider yields multiple packages with the same name from GetInstalledPackages, Get-Package only returns one instance with each name (it appears to be the one with the greatest version, which is odd because oneget may not know how to interpret the version numbers). There should be a way for providers to correctly report that multiple instances of a package are installed.

This can happen in https://github.com/madewokherd/oneget-python, when multiple versions of Python are installed. Each instance of Python may have its own install of a wheel package, for example I have pbr 1.7.0 installed in Python 3.4.2, and pbr 0.11.0 installed in Python 2.7.10.

It used to be possible to see all of the installed packages, however I never did figure out a good way to express their location.

**Comment by jianyunt** [comment]
To add a switch like allversions, e.g, get-package -allversions that will return all installed versions of a package would be nice. is this something you are looking for.  Working on the fix.

**Comment by madewokherd** [comment]
That would work.
