### ISSUE TITLE
Install-Package ignores -WhatIf when -Force is present.

### ISSUE THREAD

**Issue by Jaykul** [OneGet/oneget#151]
Currently, using -WhatIf doesn't work if -Force is present. That's an incorrect implementation of ShouldProcess.  -Force can override a `ShouldContinue` prompt, but it *must not* override ShouldProcess (we have `ConfirmPreference` for that).

Scripters **must** be able to add -WhatIf to any command that has it and run it without _any_ risk of changes being made.  

That should, for what it's worth, also prevent installation of "bootstrap" stuff.

For example, this command should NOT install, but does:
```
Install-Package -Name $Name -Force -ForceBootstrap -Destination $Destination -ProviderName NuGet -Source 'https://www.nuget.org/api/v2' -Verbose -WhatIf 
VERBOSE: NuGet: Installing 'Newtonsoft.Json 7.0.1'.
VERBOSE: NuGet: Successfully installed 'Newtonsoft.Json 7.0.1'.
```

**Comment by quoctruong** [comment]
Hi Jay,

Thanks for opening the bug. We will provide a fix soon.

**Comment by quoctruong** [comment]
This is fixed in the new source code uploaded
