### ISSUE TITLE
Using PackageManagement / OneGet

### ISSUE THREAD

**Issue by MarkusAmshove** [OneGet/oneget#152]
Hello guys!

First of all thanks for that project, I'm already testing and using it a lot ;)

I'm playing around with the PackageManagement and trying to use it in an application.

What I'm doing at the moment ist interopting with the powershell via "System.Management.Automation", but it is kinda error prone to convert the PSObjects, which are converted C#-Objects, back to C# objects.

Is there already a way to use the PackageManagement.dll?

I'm not getting it to work. If I clone your repository and reference the whole solution I'm not really sure on how to use it.

If I use the PackageManager.Instance I only get nulls (OneGet/PackageManagement is installed on the development machine)

Is this just not possible yet?

greets

**Comment by quoctruong** [comment]
Hi Markus, the PackageManager class is internal so you can't get it on the powershell cmdline. If you want to play around with it maybe you can change it to public and recompile it?

**Comment by MarkusAmshove** [comment]
Hello, 

what I wanted to say is that I can use PackageManagement from C# if I invoke the Powershell via C#, for example to get the list of all package providers. 

But if I change the class PackageManager to public and use it, everything returns null, as there are no providers etc. 

What would I need to do to initialize it correctly? 

In short:
Powershell cmdlets work fine, if I use the PackageManager class I don't get results (on the same computer)

**Comment by quoctruong** [comment]
Hi Markus, there are public API call to import package providers. Have you tried using those?

**Comment by MarkusAmshove** [comment]
Hi Quoctruong,

I thought that if I use the PackageManager in C# I get the same results as using the Powershell cmdlets, as it's the same machine.

If I use:

    static void Main(string[] args)
    {
    	var mng = PackageManager.Instance;
    	Console.WriteLine(mng.PackageProviders.First());
    }

I get a System.InvalidOperationException because the sequence is empty.

If I use Get-PackageProvider in the Powershell I get:

![unbenannt](https://cloud.githubusercontent.com/assets/2401875/10669325/86109354-78e0-11e5-9c2f-7b452fe48178.PNG)


Do I need to instanciate anything in C# before I can use the PackageManager class?

**Comment by quoctruong** [comment]
Hi Markus, you have to import your providers first before you can use them. Please see the ImportPackageProvider method in PackageManagementService. If you want to see how this is used, please take a look at the ImportPackageProvider.cs file in PowerShell.Module project.

**Comment by MarkusAmshove** [comment]
Hey quoctruong,

I understand how to use the API now, thanks :+1: :)
