### ISSUE TITLE
Publish-Module doesn't seem to publish help

### ISSUE THREAD

**Issue by heaths** [OneGet/oneget#155]
I have a help file in my module named something like _mydll_.dll-help.xml and it works fine when in the module directory; however, after running `publish-module` it seems that file wasn't packaged and pulled down later with `install-module`. The file is listed in the module manifest in the `FileList` property.

See the 'msi' module in the gallery if you want to review the manifest.

**Comment by heaths** [comment]
Upon further investigation, piping a `PSModuleInfo` object to `Publish-Module` actually binds to the `Name` parameter, which causes `Publish-Module` to look up the module, which in my case didn't have the help XML because the original uploaded module didn't have it.

When using the `Path` parameter, there is a bug that assumes that the parent directory name of the .psd1 file is the module name (instead of, logically, the name of the file). But when building projects, the parent directory name is likely 'Debug' or 'Release'. This needs to be fixed.

When debugging this, if I change `$manifestPath` in `Publish-Module`, the scenario works correctly...though one may want to (optionally) exclude files like *.pdb.

I will try to get a PR for this, but given the dependency on having the PowerShellGet module I may just construct the NuPkg myself for my project so I don't need to install additional dependencies via AppVeyor.

**Comment by quoctruong** [comment]
Hi heaths, thanks for investigating the bugs. I will point this out to the owner of the PowerShellGet module (this repository is mostly for PackageManagement work, we don't have a repository for PowerShellGet yet).

**Comment by jianyunt** [comment]
This issue was moved to PowerShell/PowerShellGet#50
