### ISSUE TITLE
Need new verb "Validate" in Update-ScriptFileInfo

### ISSUE THREAD

**Issue by MaxTrinidad** [OneGet/oneget#156]
Currently the cmdlet Update-ScriptFileInfo serves two purpose: to validate and update. We need a new "Validate" verb to separate the two purpose function in this particular cmdlet. 

Update-ScriptFileInfo
Syntax
    Update-ScriptFileInfo [-Path] <String> [-Version <Version>] [-Author <String>] [-Guid <Guid>] [-Description 

<String>] [-CompanyName <String>] [-Copyright <String>] [-RequiredModules <Object[]>] [-ExternalModuleDependencies 

<String[]>] [-RequiredScripts <String[]>] [-ExternalScriptDependencies <String[]>] [-Tags <String[]>] [-ProjectUri 

<Uri>] [-LicenseUri <Uri>] [-IconUri <Uri>] [-ReleaseNotes <String[]>] [-PassThru ] [-Force ] [-WhatIf ] [-Confirm ] 

[<CommonParameters>]

    Update-ScriptFileInfo [-LiteralPath] <String> [-Version <Version>] [-Author <String>] [-Guid <Guid>] [-Description 

<String>] [-CompanyName <String>] [-Copyright <String>] [-RequiredModules <Object[]>] [-ExternalModuleDependencies 

<String[]>] [-RequiredScripts <String[]>] [-ExternalScriptDependencies <String[]>] [-Tags <String[]>] [-ProjectUri 

<Uri>] [-LicenseUri <Uri>] [-IconUri <Uri>] [-ReleaseNotes <String[]>] [-PassThru ] [-Force ] [-WhatIf ] [-Confirm ] 

[<CommonParameters>]

At the same time this new verb could apply to any existing and new cmdlets.

Existing cmdlet: Update-ScriptFileInfo 
New verb in cmdlet: Validate-ScriptFileInfo

**Comment by Jaykul** [comment]
It would need to be "Confirm" -- the naming guidelines specifically say:

> **Confirm (cn)** Acknowledges, verifies, or validates the state of a resource or process.
> For this action, do not use verbs such as Acknowledge, Agree, Certify, Validate, or Verify.

**Comment by GoateePFE** [comment]
Can this be closed now that we have Test-ScriptFileInfo?

**Comment by bmanikm** [comment]
Test-ScriptFileInfo cmdlet is for validating the script file info/metadata.
