### ISSUE TITLE
Web site references non-existent parameter

### ISSUE THREAD

**Issue by heaths** [OneGet/oneget#160]
Related to #159, the web site [says](https://www.powershellgallery.com/packages/MSI/3.0.0-pre0013) you can install pre-releases of packages by specifying `-Pre` to `Install-Package`, but this parameter does not exist with the current WMF 5.0 and the PackageManagement module.

**Comment by jianyunt** [comment]
Looks like these information in the [site](https://www.powershellgallery.com/packages/MSI/3.0.0-pre0013) were generated by the nuget backend, not through PowerShellGet. The author possibly directly uses the nuget.exe to publish the MSI package. If you use publish-module (which is a recommend way to do), you will get the correct info.

**Comment by heaths** [comment]
I'm the module owner, and I did publish directly because `publish-module` has bugs that prevent me from publishing without several workarounds. But I don't see what that has to do with incorrect documentation about a `-Pre` parameter that isn't defined.

The module works fine when not using a semver.

**Comment by jianyunt** [comment]
Hi Heaths, can you tell us what's the problem you encountered while publish-module?
Powershellgallery.com does not support semver as PowerShell does not. Also powershellgallery.com is based on Nuget V2 so people can use nuget.exe to publish packages. I think powershellgallery.com backend can use the module version in the module manifest to workaround this issue. 
-Pre is not supported.

Thanks.

**Comment by heaths** [comment]
I've started a thread internally with the module owners about it. There's several problems. But this bug is specifically about `-Pre` mentioned in official documentation (i.e. the web site) but is not supported by either `install-package` (OneGet) or `install-module` (PowerShellGet); hence, mentioning it on the web site should be removed.

**Comment by jianyunt** [comment]
The site is delisted already. But we can not delete the module published in the PowerShellGallery.com.
