### ISSUE TITLE
Get-PackageProvider list providers available to install

### ISSUE THREAD

**Issue by Rast1234** [OneGet/oneget#162]
Hello. `Get-PackageProvider` itself lists only installed providers. Is there any way to list known providers that can be downloaded? It seems very cryptic to google for "oneget chocolatey" and find out that OneGet can download the provider automagically if you tell it `Get-PackageProvider chocolatey`.

How did it know where to look for the provider binary? How to discover other providers from the same place? I found the `https://github.com/OneGet/ProviderRegistry`, but no documentation and no options for `Get-PackageProvider`.

**Comment by quoctruong** [comment]
Hi Rast1234,

Have you tried the cmdlet Find-PackageProvider?

**Comment by Rast1234** [comment]
I have no such cmdlet on Win10. I have an old version?

**Comment by jianyunt** [comment]
Rast1234, 

In Win10, there is no find-packageprovider cmdlet. You can install [WMF 5.0 Product Preview](https://www.microsoft.com/en-us/download/details.aspx?id=48729) to use find-packageprovider, install-packageprovider, import-packageproivder, and get-packageprovider -listavailable.

Find-Packageprovider returns a list of Package Management package providers available for installation. Currently OneGet looks the providers in the PowerShellGallery.com and our Azure blob store. You can use install-packageprovider to install the provider. 

Example:
Find-PackageProvider 
Find-PackageProvider –Name "Nuget" -AllVersions
Install-PackageProvider -Name "Nuget" -RequiredVersion "2.8.5.201" -Force

**Comment by jianyunt** [comment]
Sorry. This feature will be in the WMF 5.0 RTM. It will be released soon. Just watch out the news in the PowerShell blog site.

However we have published the OneGet source with the above features already at https://github.com/oneget/oneget. You can follow 'Building the code' in the OneGet site to compile and deploy the code on your machine to try out.

**Comment by Rast1234** [comment]
Understood, thanks!
