### ISSUE TITLE
NuGet provider version 2.8.5.202 is broken

### ISSUE THREAD

**Issue by uncleyo** [OneGet/oneget#163]
Hi, not sure if this issue should be registered here or elsewhere, but I'll try.

Latest NuGet provider build (2.8.5.202) seems to be broken.
It spits different errors and warnings depending on the package you are trying to install/uninstall from PSGallery.
Some examples:
`WARNING: Cannot bind argument to parameter 'null' because it is an empty string` for `posh-git`
or
`WARNING: The property 'LocalName' cannot be found on this object. Verify that the property exists.` followed by the same message as an error this time for `xWebAdministration`.

Removing 2.8.5.202 and installing 2.8.5.201 fixes the errors.

**Comment by quoctruong** [comment]
Hi uncleyo,

This is fixed now. Please try NuGet provider 2.8.5.202 again.

Thanks!
