### ISSUE TITLE
uninstall-package -version X just uninstalls the latest version

### ISSUE THREAD

**Issue by jianyunt** [OneGet/oneget#167]
See uservoice feedback:

https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11673816-uninstall-package-version-is-evil

The proposal fix is to make Version to be an alias for RequiredVersion

**Comment by KirkMunro** [comment]
Also see the comments on that suggestion.  I think it might be better to simply remove the -Version alias altogether rather than to have -Version mean -RequiredVersion in one command and -MinimumVersion in another.

**Comment by jianyunt** [comment]
To keep the -Version is primarily for the backward compat (as we shipped PackageManagement in Win10 already).
we will change the version as an alias for the requiredversion for all PackageManagement cmdlets.

**Comment by jianyunt** [comment]
We revisited this topic and decided to remove the -Version alias altogether in PackageManagement and PowerShellGet cmdlets.

**Comment by jianyunt** [comment]
Removed -version alias in OneGet and PSGet. Published PackageMangement source code. You download, build and try it out. The official PackageManagement binaries will be in TP5 Server release soon.
