### ISSUE TITLE
Possible to use PSGet behind a proxy?

### ISSUE THREAD

**Issue by kamranayub** [OneGet/oneget#171]
I'm running into an issue trying to use PowerShellGet on a build server that is behind a proxy. I figured since PSGet is powered by Nuget, there might be a way to provide the proxy information.

Here's what I see when I try to execute `Install-PackageProvider -Name NuGet -Force`

```
WARNING: Unable to download the list of available providers. Check your internet connection.
DEBUG: 00:00:49.6183191 Timed out downloading 
'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409'
DEBUG: 00:00:51.2711916 Ping-Endpoint: 
location=https://go.microsoft.com/fwlink/?LinkID=622995&clcid=0x409, statuscode=, resolvedLocation=
DEBUG: 00:00:51.2991522 OPTION: Force => True
DEBUG: 00:00:51.2993697 OPTION: Name => NuGet
DEBUG: 00:00:51.3252253 PowerShell Script 'PSModule' Function 'Find-Package' returns null.
DEBUG: 00:00:51.3261755 Done calling powershell ®Find-Package¯ ®PSModule¯
Install-PackageProvider : No match was found for the specified search criteria for the provider 
'NuGet'. The package provider requires 'PackageManagement' and 'Provider' tags. Please check if 
the specified package has the tags.
```

I do have a machine-wide Nuget.config in my AppData\Roaming\Nuget folder, but I'm guessing this is separate.

By the way, this would be related to #141 except we don't set a system-wide proxy setting. I _was_ able to workaround this by setting the proxy settings in IE for the user running the build--but I still suggest some way of providing proxy information specifically to the calls involved using PSGet, similar to Nuget.

**Comment by jianyunt** [comment]
We plan to support proxy and proxy auth.

**Comment by kamranayub** [comment]
Great! That would be helpful.

**Comment by jianyunt** [comment]
@kamranayub,  the Proxy and auth  is supported in [WMF 5.1]
(https://blogs.msdn.microsoft.com/powershell/2016/07/16/announcing-windows-management-framework-wmf-5-1-preview/).

In WMF 5.1, OneGet supports finding and installing packages from a repository that requires basic authentication. You can supply your credentials to the Find-Package and Install-Package cmdlets. For example:
```PowerShell
Find-Package -Source <SourceWithCredential> -Credential (Get-Credential)
```
OneGet now takes new proxy parameters: -ProxyCredential and -Proxy. Using these parameters, you can specify the proxy URL and credentials to OneGet cmdlets. By default, system proxy settings are used. For example:
```PowerShell
Find-Package -Source http://www.nuget.org/api/v2/ -Proxy http://www.myproxyserver.com -ProxyCredential (Get-Credential)
```

**Comment by Plork** [comment]
This work's now for packages but I still have issues with bootstrapping nuget as part of the CD/CI process behind a corp. proxy.

**Comment by jianyunt** [comment]
@Plork, bootstrapping should be supported too. What issues you are hitting?

**Comment by happysysadm** [comment]
I have the same issue on a vanilla windows 2016 version 1607 build 14393.447.
I am behind a corporate proxy and I get:

`Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force -Verbose -proxy proxy.corp.com:8080 -Credential $cred`

> VERBOSE: Using the provider 'Bootstrap' for searching packages.
VERBOSE: Finding the package 'Bootstrap::FindPackage' 'NuGet','','2.8.5.201','''.
WARNING: Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.
VERBOSE: Cannot download link 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409', retrying for '2' more times.
VERBOSE: Cannot download link 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409', retrying for '1' more times.
VERBOSE: Cannot download link 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409', retrying for '0' more times.
WARNING: Unable to download the list of available providers. Check your internet connection.
Install-PackageProvider : No match was found for the specified search criteria for the provider 'NuGet'. The package provider requires 'PackageManagement' and 'Provider' tags. Please check if the specified package has the tags.
At line:1 char:1
+ Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power...PackageProvider:InstallPackageProvider) [Install-PackageProvider], Exception
    + FullyQualifiedErrorId : NoMatchFoundForProvider,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackageProvider

**Comment by jianyunt** [comment]
NuGet 2.8.5.201  does not support proxy. Please try

Install-PackageProvider -Name NuGet -force -verbose

This cmdlet should pull down the latest nuget provider.

To be sure you are using the latest (2.8.5.206 or later), delete nuget folder under these folder and run the install-packageprovider -name nuget -force  cmdlet.  Relaunch powershell.

$env:ProgramFiles\PackageManagement\ProviderAssemblies\nuget  or  $env:LOCALAPPDATA\PackageManagement\ProviderAssemblies\nuget.

**Comment by happysysadm** [comment]
Hello @jianyunt 
I did as you asked, but I get the same error as above:

Install-PackageProvider -name nuget -force -verbose
WARNING: MSG:UnableToDownload «https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409» «»
VERBOSE: Cannot download link 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409', retrying for '2' more
times.
VERBOSE: Cannot download link 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409', retrying for '1' more
times.
VERBOSE: Cannot download link 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409', retrying for '0' more
times.
WARNING: Unable to download the list of available providers. Check your internet connection.
VERBOSE: Using the provider 'Bootstrap' for searching packages.
VERBOSE: Finding the package 'Bootstrap::FindPackage' 'nuget','','','''.
WARNING: Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.
VERBOSE: Cannot download link 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409', retrying for '2' more
times.
VERBOSE: Cannot download link 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409', retrying for '1' more
times.
VERBOSE: Cannot download link 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409', retrying for '0' more
times.
Install-PackageProvider : No match was found for the specified search criteria for the provider 'nuget'. The package
provider requires 'PackageManagement' and 'Provider' tags. Please check if the specified package has the tags.
At line:1 char:1
+ Install-PackageProvider -name nuget -force -verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power...PackageProvider:InstallPackageProvider) [Install-Pac
   kageProvider], Exception
    + FullyQualifiedErrorId : NoMatchFoundForProvider,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackagePro
   vider

Any idea?

**Comment by mithunphilip1984** [comment]
Hi Happysysadmin, Did you find any solution for this? I am getting the same error

**Comment by jianyunt** [comment]
I think you need to provide proxy uri and credential.
see syntax: https://msdn.microsoft.com/en-us/powershell/reference/5.1/powershellget/install-module

also  see https://github.com/OneGet/oneget/wiki/Q-and-A in 
"Sample usage with proxy"

However to use the above feature, you need WMF 5.1, or Windows Server 2016, or the PowerShellGet and PackageManagement modules in the PowerShellGallery.com should work. Please note the NuGet provider needs to be 2.8.5.206 or later. 

Looking at  "gcm install-packageprovider -Syntax", you can provide proxy and proxy cred for installing the nuget provider as long as you are on WMF5.1, Server 2016, Win10 Anniversary, or modules from the gallery.

**Comment by gaelcolas** [comment]
@jianyunt and @happysysadm: I did test this, and it works behind a proxy, but there's further complications.
First of all, sometimes that address `https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409` is in a blocked category in the proxy by default, so it needs to be whitelisted.

Then, the current problem I have, is even if the swigtag gets resovled, it then tries to bootstrap and looks (as it should) in my internal repos (as registered package sources), but that proxy configuration (the `-proxy`) does not bypass local addresses... so it tries to resolve the https://my/local/repo via the proxy, and fail (obviously).

It is wrong to assume people have access to internet (even behind proxy) during the bootstrap process, and the swigtag resolution should be avoidable (like specifying a manual entry).

This is a major blocker for automating windows configuration in secure environment, as we get to that chicken and egg problem (from a clean windows with only WMF5.1, no Internet but local repos):
- I want to install packages
- I need ChocolateyGet provider (I can install module from my internal PS repo)
- ChocolateyGet needs choco.exe, wants to run https://Chocolatey.org/install.ps1
- To install Choco.exe I need to install its package from my feed, I could try Chocolatey Provider
- To install Chocolatey Provider, I need to access the swigtag ---> End of story

If I'm behind a proxy, but want to use local repos, I access the swidtag, that links to other swidtags (all needing to be allowed through the proxy, which is https://oneget.org/*) before I can hope to resolve to https://oneget.org/ChocolateyPrototype-2.8.5.130.exe, download and install...

I've seen that  there's a Bootstrap provider hidden there:
```PowerShell
PS C:\> get-packageProvider -name Bootstrap

Name                     Version          DynamicOptions
----                     -------          --------------
Bootstrap                3.0.0.0          DestinationPath, Scope, DisplayLongSourceName
```

Is there a way to override its functionalities? 
How could we bootstrap without internet access?

Please bear in mind that this should ultimately be done via DSC, and cannot be pre-baked into the Windows image.

**Comment by gaelcolas** [comment]
Forgot to mention that pulling the Chocolatey package with Nuget from my local repo, renaming to `.zip`,  expanding the archive, executing the `ChocolateyInstall.ps1`, is not what I'd call an elegant solution. :)
Even if that should work...

**Comment by Plork** [comment]
This is your only option I think to bootstrapping nuget after Imaging.
https://github.com/OneGet/oneget/wiki/Q-and-A#how-do-i-install-a-package-provider-such-as-nuget-provider-if-i-do-not-have-internet-connection-on-my-box

For chocolatey I did pull the choco package to my local repo. Downloaded the install.ps1 ... changed the url to 7za.exe and chocolatey to my internal repo and during my Packer build I run:

`iex ((New-Object System.Net.WebClient).DownloadString('https://internalserver.local/install.ps1'))`

**Comment by jianyunt** [comment]
@gaelcolas and  @Plork,  what's Plork mentioned is the way I can think of for bootstrapping for machines without the Internet.

I suggest do not use ChocolateyProtypotype provider because it only works with some Chocolatey packages. Rob, a Chocolatey owner,  is working on OneGet-Chocolatey provider. Until then,  I recommend to use ChocolateyGet for the time being. You are right ChocolateyGet  depends on choco and it needs ChocolateyInstall.ps1.

**Comment by gaelcolas** [comment]
@jianyunt I'm afraid this is not a really good story for automating deployment, bearing in mind that the goal is to provision machines with DSC. 
ChocolateyPrototype is used only to install Choco.exe from internal NuGet feed, before we can use ChocolateyGet.

To provision machine consistently whether or not they're on DMZ, Behind proxy, or without Internet access, we need to limit the number of Required infrastructure for them.
So far, I can see that the minimum needed should probably be:
- Pull Server, delivering MOF and required Resource Modules
- Modules and Packages endpoint, used by PackageManagement (CIFS/Local/NuGet...)

Doing xRemoteFile would require the provider to be hosted somewhere else (third dependency), not very convenient, as that means extra configurations for the endpoint.

Given that the LCM pulls required Resources from PullServer, in a simplistic way (no need for NuGet), I think I will try to create a Bootstrap DSC Resource, that just installs the Basic Provider(s) and include the Dll(s) or EXEs in that module.
DSC should just pull the Bootstrap module, and Install it when a MOF tells it to do so.
Once NuGet is installed, we can pull PS modules (i.e. ChocolateyGet).
Once ChocolateyPrototype.exe provider is installed, we can install *some* packages (i.e. Chocolatey to get the real `Choco.exe`, and finally use ChocolateyGet pre-bootstrapped).

/cc @ferventCoder again, because that scenario means the Chocolatey Package should _always_ be backward compatible with ChocolateyPrototype (so that any WMF5.1 can bootstrap this way), and the logic could be used in [cChocoInstaller](https://github.com/chocolatey/cChoco/blob/development/DSCResources/cChocoInstaller/cChocoInstaller.psm1).

**Comment by ferventcoder** [comment]
@gaelcolas let me recommend you use an internal script with cChocoInstaller pointing to a chocolatey.nupkg file that is gathered from an internal location. This is 100% reliable. https://chocolatey.org/install#completely-offline-install

**Comment by ferventcoder** [comment]
> that scenario means the Chocolatey Package should always be backward compatible with ChocolateyPrototype (so that any WMF5.1 can bootstrap this way), and the logic could be used in cChocoInstaller

@gaelcolas the ChocolateyPrototype was designed by Microsoft and was a non-fully functional prototype when it was designed and then features/security/bug fixes over the last 3 years would make me very wary of using it at all. If you can get it to work, great! However its use is not supported in any way by the Chocolatey team (because it was a prototype and didn't come from the Chocolatey team), so we are unlikely to guarantee any kind of compatibility.

That's why we recommend using ChocolateyGet until the official provider is available (which will be supported). HTH

> Forgot to mention that pulling the Chocolatey package with Nuget from my local repo, renaming to .zip, expanding the archive, executing the ChocolateyInstall.ps1, is not what I'd call an elegant solution. :)

I prefer approaches that require zero internet, which means you may need to give up some of the elegance of getting Chocolatey installed the way the community does by way of internet access. Reinventing some of that locally is a good way forward.

**Comment by jianyunt** [comment]
Chocolatey provider is a prototype provider created by OneGet team and is on path for deprecation. Please work with Chocolatey owners to get official support.

**Comment by davidjmckinnon** [comment]
If you're reading this, you are most likely having issues at your company while attempting to install providers or modules from behind a proxy and possibly receiving:

"**_Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409'_**"

 - the Note below may pertain to you...

*** Important Note: Sysadmin Accounts May Be Blocked By Your Company While Standard Accounts Are Allowed To Access The Internet - are you attempting to install powershell providers using your sysadmin account? - oops! ***


My Company uses Autoconfig proxy PAC files on workstations and a static proxy on servers – I located the following Powershell entries that worked for me on my Windows 10 client running PS5.1:

	PAC Server:	http://pac_server.net/domain.pac
	portqry.exe -n pac_server.net -e 80 -p TCP	(portqry.exe is a free microsoft port utility)
	  TCP port 80 (http service): LISTENING

The x.x.x.x below is the IP Address and port of the PAC server:

===============================

[system.net.webrequest]::defaultwebproxy = new-object system.net.webproxy('http://x.x.x.x:80')
[system.net.webrequest]::defaultwebproxy.credentials = [System.Net.CredentialCache]::DefaultNetworkCredentials
[system.net.webrequest]::defaultwebproxy.BypassProxyOnLocal = $true

================================

Command:

Invoke-WebRequest http://github.com|select RawContent

Output:

RawContent
———-
HTTP/1.1 200 OK…

I spent some time trying different options – I hope this can help someone out there in la-la land… Dave
