### ISSUE TITLE
Unable to save or install azure module

### ISSUE THREAD

**Issue by eosfor** [OneGet/oneget#175]
Here is the debug output

PS X:\> save-Module -Name Azure -Path "E:\temp\Azure 1.3.1" -Verbose -Debug
DEBUG: 00:00:00 Calling New() : MethodName = 'GetDynamicOptions'

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: 00:00:00.0000213 Verbose: True
DEBUG: 00:00:00.0000337 Path: E:\temp\Azure 1.3.1
DEBUG: 00:00:00.0000445 Name: Azure
DEBUG: 00:00:00.0000542 Debug: True
DEBUG: 00:00:00.0006682 INVOKING PowerShell Fn Get-DynamicOptions with args Provider that has length 1
DEBUG: 00:00:00.0011164 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0023125 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0042137 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0042315 Verbose: True
DEBUG: 00:00:00.0042420 Path: E:\temp\Azure 1.3.1
DEBUG: 00:00:00.0042514 Name: Azure
DEBUG: 00:00:00.0042607 Debug: True
DEBUG: 00:00:00.0046593 INVOKING PowerShell Fn Get-DynamicOptions with args Source that has length 1
DEBUG: 00:00:00.0050729 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0067458 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0125759 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0125970 Verbose: True
DEBUG: 00:00:00.0126078 Path: E:\temp\Azure 1.3.1
DEBUG: 00:00:00.0126181 Name: Azure
DEBUG: 00:00:00.0126277 Debug: True
DEBUG: 00:00:00.0132098 INVOKING PowerShell Fn Get-DynamicOptions with args Package that has length 1
DEBUG: 00:00:00.0136216 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0159844 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:02.6103854 Calling SearchForPackages. Name='Azure'
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
DEBUG: 00:00:02.6120894 PackageProvider::FindPackage with name Azure
DEBUG: 00:00:02.6127383 Calling SearchForPackages After Select 1
DEBUG: 00:00:02.6155566 Calling New() : MethodName = 'FindPackage'
DEBUG: 00:00:02.6166650 ProviderName: PowerShellGet
DEBUG: 00:00:02.6171675 Type: Module
DEBUG: 00:00:02.6176826 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:02.6234124 Debug: True
DEBUG: 00:00:02.6251079 Path: E:\temp\Azure 1.3.1
DEBUG: 00:00:02.6332083 Verbose: True
DEBUG: 00:00:02.6361182 Name: Azure
DEBUG: 00:00:02.6408830 INVOKING PowerShell Fn Find-Package with args System.String[], , ,  that has length 4
DEBUG: 00:00:02.6439986 In PowerShellGet Provider - 'Find-Package'.
DEBUG: 00:00:02.6462295 OPTION: ProviderName => PowerShellGet
DEBUG: 00:00:02.6490427 OPTION: Type => Module
DEBUG: 00:00:02.6517562 OPTION: MessageResolver => Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:02.6538165 OPTION: Debug => True
DEBUG: 00:00:02.6556846 OPTION: Path => E:\temp\Azure 1.3.1
DEBUG: 00:00:02.6575389 OPTION: Verbose => True
DEBUG: 00:00:02.6589055 OPTION: Name => Azure
VERBOSE: The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2/' and PackageManagementProvider is 'NuGet'.
DEBUG: 00:00:02.6706798 PackageProvider::FindPackage with name Azure
DEBUG: 00:00:02.6840800 Calling 'NuGet'::'FindPackage' - name='Azure', requiredVersion='',minimumVersion='', maximumVersion='''.
DEBUG: 00:00:02.6863846 Iterating 'Azure'.
DEBUG: 00:00:02.6882434 There are '1' registered sources in 'NuGet' provider.
DEBUG: 00:00:02.6898242 Source 'https://www.powershellgallery.com/api/v2/' is not one of the registered sources in 'NuGet' provider.
DEBUG: 00:00:04.3494446 Source 'https://www.powershellgallery.com/api/v2/' is validated.
DEBUG: 00:00:04.3504746 Calling 'NuGetRequest'::'GetPackageById', 'Azure'.
DEBUG: 00:00:04.6049705 Calling 'HttpClientPackageRepository'::'FindPackagesById', 'Azure'.
DEBUG: 00:00:04.6063672 Calling 'NuGetClient'::'FindPackage'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Azure'' for ''.
DEBUG: 00:00:04.6077298 Downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Azure'&$skip=0&$top=40'.
DEBUG: 00:00:05.6337635 Completed downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Azure'&$skip=0&$top=40'.
DEBUG: 00:00:05.6481271 '10' packages recevied in the last request.
VERBOSE: Total package yield:'1' for the specified package 'Azure'.
DEBUG: 00:00:05.6677192 Completed iterating for 'Azure'.
DEBUG: 00:00:05.6742033 Done calling powershell «Find-Package» «PSModule»

Confirm
Are you sure you want to perform this action?
Performing the operation "Save Package" on target "E:\temp\Azure 1.3.1".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: 00:00:08.4853664 Calling New() : MethodName = 'DownloadPackage'
DEBUG: 00:00:08.4876261 ProviderName: PowerShellGet
DEBUG: 00:00:08.4885224 Type: Module
DEBUG: 00:00:08.4893620 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:08.4905156 Debug: True
DEBUG: 00:00:08.4913010 Path: E:\temp\Azure 1.3.1
DEBUG: 00:00:08.4921430 Verbose: True
DEBUG: 00:00:08.4943729 Name: Azure
DEBUG: 00:00:08.4973398 INVOKING PowerShell Fn Download-Package with args NuGet|Azure|1.3.1|https://www.powershellgallery.com/api/v2/|Module, E:\temp\Azure 1.3.1 that has length 2
DEBUG: 00:00:08.4995339 In PowerShellGet Provider - 'Download-Package'.
DEBUG: 00:00:08.5018985 In PowerShellGet Provider - 'Install-PackageUtility'.
DEBUG: 00:00:08.5042128 The FastPackageReference is 'NuGet|Azure|1.3.1|https://www.powershellgallery.com/api/v2/|Module'.
DEBUG: 00:00:08.5062804 OPTION: ProviderName => PowerShellGet
DEBUG: 00:00:08.5084715 OPTION: Type => Module
DEBUG: 00:00:08.5107665 OPTION: MessageResolver => Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:08.5127871 OPTION: Debug => True
DEBUG: 00:00:08.5142777 OPTION: Path => E:\temp\Azure 1.3.1
DEBUG: 00:00:08.5174166 OPTION: Verbose => True
DEBUG: 00:00:08.5193622 OPTION: Name => Azure
VERBOSE: The specified module will be installed in 'E:\temp\Azure 1.3.1'.
DEBUG: 00:00:08.5228833 ArtfactType is Module
VERBOSE: The specified Location is 'NuGet' and PackageManagementProvider is 'NuGet'.
VERBOSE: Downloading module 'Azure' with version '1.3.1' from the repository 'https://www.powershellgallery.com/api/v2/'.
DEBUG: 00:00:08.5370322 Calling 'NuGet'::'InstallPackage', '$aHR0cHM6Ly93d3cucG93ZXJzaGVsbGdhbGxlcnkuY29tL2FwaS92Mi8=\QXp1cmU=\MS4zLjE=\aHR0cHM6Ly93d3cucG93ZXJzaGVsbGdhbGxlcnkuY29tL2FwaS92Mi8='.
DEBUG: 00:00:08.5391651 Calling 'NuGetRequest'::'GetPackageByFastpath', '$aHR0cHM6Ly93d3cucG93ZXJzaGVsbGdhbGxlcnkuY29tL2FwaS92Mi8=\QXp1cmU=\MS4zLjE=\aHR0cHM6Ly93d3cucG93ZXJzaGVsbGdhbGxlcnkuY29tL2FwaS92Mi8='.
DEBUG: 00:00:08.5415343 Calling 'NuGetRequest'::'ResolvePackageSource', 'https://www.powershellgallery.com/api/v2/'.
DEBUG: 00:00:08.5438441 Calling 'NuGetRequest'::'FindRegisteredSource', 'https://www.powershellgallery.com/api/v2/'.
DEBUG: 00:00:08.5461427 Source 'https://www.powershellgallery.com/api/v2/' is not one of the registered sources in 'NuGet' provider.
DEBUG: 00:00:09.4385566 Calling 'HttpClientPackageRepository'::'FindPackage', 'Azure'.
DEBUG: 00:00:09.4402084 Calling 'NuGetClient'::'FindPackage'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Azure'' for ''.
DEBUG: 00:00:09.4417093 Downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Azure'&$skip=0&$top=40'.
DEBUG: 00:00:10.6144362 Completed downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Azure'&$skip=0&$top=40'.
DEBUG: 00:00:10.6340913 '10' packages recevied in the last request.
DEBUG: 00:00:10.6417394 'Package version' is '1.3.1'.
DEBUG: 00:00:10.6441411 'Request's Destination' is 'C:\Users\Andrey\AppData\Local\Temp\1929385627'.
DEBUG: 00:00:10.6476234 Calling 'NuGetClient'::'GetPackageDependencies'.
DEBUG: 00:00:10.6506105 There are '1' registered sources in 'NuGet' provider.
DEBUG: 00:00:10.6530766 Source 'https://www.powershellgallery.com/api/v2/' is not one of the registered sources in 'NuGet' provider.
DEBUG: 00:00:10.9186834 Source 'https://www.powershellgallery.com/api/v2/' is validated.
DEBUG: 00:00:10.9198376 Calling 'NuGetRequest'::'GetPackageById', 'Azure.Storage'.
DEBUG: 00:00:11.1733863 Calling 'HttpClientPackageRepository'::'FindPackagesById', 'Azure.Storage'.
DEBUG: 00:00:11.1751689 Calling 'NuGetClient'::'FindPackage'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Azure.Storage'' for ''.
DEBUG: 00:00:11.1781110 Downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Azure.Storage'&$skip=0&$top=40'.
DEBUG: 00:00:11.3344582 Completed downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Azure.Storage'&$skip=0&$top=40'.
DEBUG: 00:00:11.3364074 '9' packages recevied in the last request.
DEBUG: 00:00:11.3375163 There are '1' registered sources in 'NuGet' provider.
DEBUG: 00:00:11.3386162 Source 'https://www.powershellgallery.com/api/v2/' is not one of the registered sources in 'NuGet' provider.
DEBUG: 00:00:11.6152270 Source 'https://www.powershellgallery.com/api/v2/' is validated.
DEBUG: 00:00:11.6169521 Calling 'NuGetRequest'::'GetPackageById', 'AzureRM.Profile'.
DEBUG: 00:00:11.8719532 Calling 'HttpClientPackageRepository'::'FindPackagesById', 'AzureRM.Profile'.
DEBUG: 00:00:11.8737201 Calling 'NuGetClient'::'FindPackage'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='AzureRM.Profile'' for ''.
DEBUG: 00:00:11.8752216 Downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='AzureRM.Profile'&$skip=0&$top=40'.
DEBUG: 00:00:12.0237293 Completed downloading 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='AzureRM.Profile'&$skip=0&$top=40'.
DEBUG: 00:00:12.0254860 '9' packages recevied in the last request.
DEBUG: 00:00:12.0271764 Returning the call 'NuGetClient'::'GetPackageDependencies'.
DEBUG: 00:00:12.0590245 Calling 'NuGetClient'::'InstallPackage'.
VERBOSE: InstallPackage' - name='AzureRM.profile', version='1.0.6',destination='C:\Users\Andrey\AppData\Local\Temp\1929385627'
VERBOSE: DownloadPackage' - name='AzureRM.profile', version='1.0.6',destination='C:\Users\Andrey\AppData\Local\Temp\1929385627\AzureRM.profile\AzureRM.profile.nupkg',
uri='https://www.powershellgallery.com/api/v2/package/AzureRM.profile/1.0.6'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/AzureRM.profile/1.0.6'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/AzureRM.profile/1.0.6'.
VERBOSE: Completed downloading 'AzureRM.profile'.
DEBUG: 00:00:18.2317390 Calling 'NuGetClient'::'InstallPackageLocal'.
VERBOSE: InstallPackageLocal' - name='AzureRM.profile', version='1.0.6',destination='C:\Users\Andrey\AppData\Local\Temp\1929385627'
DEBUG: 00:00:18.2381924 C:\Users\Andrey\AppData\Local\Temp\1929385627\AzureRM.profile\AzureRM.profile.nupkg
DEBUG: 00:00:18.9613225 Returning the call 'NuGetClient'::'InstallPackageLocal'.
DEBUG: 00:00:19.0287969 Returning the call 'NuGetClient'::'InstallSinglePackage'.
DEBUG: 00:00:19.0500194 Calling 'NuGetClient'::'InstallPackage'.
VERBOSE: InstallPackage' - name='Azure.Storage', version='1.1.0',destination='C:\Users\Andrey\AppData\Local\Temp\1929385627'
VERBOSE: DownloadPackage' - name='Azure.Storage', version='1.1.0',destination='C:\Users\Andrey\AppData\Local\Temp\1929385627\Azure.Storage\Azure.Storage.nupkg', uri='https://www.powershellgallery.com/api/v2/package/Azure.Storage/1.1.0'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/Azure.Storage/1.1.0'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/Azure.Storage/1.1.0'.
VERBOSE: Completed downloading 'Azure.Storage'.
DEBUG: 00:00:27.5456351 Calling 'NuGetClient'::'InstallPackageLocal'.
VERBOSE: InstallPackageLocal' - name='Azure.Storage', version='1.1.0',destination='C:\Users\Andrey\AppData\Local\Temp\1929385627'
DEBUG: 00:00:27.5505225 C:\Users\Andrey\AppData\Local\Temp\1929385627\Azure.Storage\Azure.Storage.nupkg
DEBUG: 00:00:29.2845557 Returning the call 'NuGetClient'::'InstallPackageLocal'.
DEBUG: 00:00:29.4783978 Returning the call 'NuGetClient'::'InstallSinglePackage'.
DEBUG: 00:00:29.4957332 Calling 'NuGetClient'::'InstallPackage'.
VERBOSE: InstallPackage' - name='Azure', version='1.3.1',destination='C:\Users\Andrey\AppData\Local\Temp\1929385627'
VERBOSE: Saving the dependency module 'AzureRM.profile' with version '1.0.6' for the module 'Azure'.
VERBOSE: DownloadPackage' - name='Azure', version='1.3.1',destination='C:\Users\Andrey\AppData\Local\Temp\1929385627\Azure\Azure.nupkg', uri='https://www.powershellgallery.com/api/v2/package/Azure/1.3.1'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/Azure/1.3.1'.
VERBOSE: Module 'AzureRM.profile' was saved successfully.
DEBUG: 00:02:09.5490400 System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.PackageManagement.NuGetProvider.PathUtility.GetHttpResponse(HttpClient httpClient, String query, Request request)
   at Microsoft.PackageManagement.NuGetProvider.NuGetClient.<DownloadDataToFileAsync>d__f.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.PackageManagement.NuGetProvider.NuGetClient.DownloadPackage(String packageName, String version, String destination, String queryUrl, NuGetRequest request, PackageSource pkgSource)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.PackageManagement.NuGetProvider.PathUtility.GetHttpResponse(HttpClient httpClient, String query, Request request)
   at Microsoft.PackageManagement.NuGetProvider.NuGetClient.<DownloadDataToFileAsync>d__f.MoveNext()
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
<---
WARNING: Package 'Azure' failed to download.

**Comment by eosfor** [comment]
This is perhaps because of some timeout

**Comment by quoctruong** [comment]
Hi @eosfor, if you try ``` Save-Package Azure -Provider NuGet -Source http://www.powershellgallery.com/api/v2/ -Path <Some test Path> -Verbose -Debug```, what do you get?

**Comment by eosfor** [comment]
PS X:\> Save-Package Azure -Provider NuGet -Source http://www.powershellgallery.com/api/v2/ -Path 'E:\temp\Azure 1.3.1' -Verbose -Debug
DEBUG: 00:00:00 Calling 'NuGet'::'ResolvePackageSources'.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: 00:00:00.0000349 There are '1' registered sources in 'NuGet' provider.
DEBUG: 00:00:00.0000551 Source 'http://www.powershellgallery.com/api/v2/' is not one of the registered sources in 'NuGet' provider.
DEBUG: 00:00:00.3737120 Source 'http://www.powershellgallery.com/api/v2/' is validated.
DEBUG: 00:00:00.3737849 Yielding the package source: '«0»'. «NuGet» «Microsoft.PackageManagement.NuGetProvider.PackageSource»
DEBUG: 00:00:00.3738024 Yielding packge source for http://www.powershellgallery.com/api/v2/ at location http://www.powershellgallery.com/api/v2/
DEBUG: 00:00:00.3738207 Returning the call 'NuGet'::'ResolvePackageSources'.
DEBUG: 00:00:03.2568924 Calling 'NuGet'::'ResolvePackageSources'.
DEBUG: 00:00:03.2569436 There are '1' registered sources in 'NuGet' provider.
DEBUG: 00:00:03.2569641 Source 'http://www.powershellgallery.com/api/v2/' is not one of the registered sources in 'NuGet' provider.
DEBUG: 00:00:03.6239950 Source 'http://www.powershellgallery.com/api/v2/' is validated.
DEBUG: 00:00:03.6240640 Yielding the package source: '«0»'. «NuGet» «Microsoft.PackageManagement.NuGetProvider.PackageSource»
DEBUG: 00:00:03.6240845 Yielding packge source for http://www.powershellgallery.com/api/v2/ at location http://www.powershellgallery.com/api/v2/
DEBUG: 00:00:03.6241161 Returning the call 'NuGet'::'ResolvePackageSources'.
DEBUG: 00:00:03.6243336 Calling SearchForPackages. Name='Azure'
VERBOSE: Using the provider 'NuGet' for searching packages.
DEBUG: 00:00:03.6252142 PackageProvider::FindPackage with name Azure
DEBUG: 00:00:03.6254354 Calling SearchForPackages After Select 1
DEBUG: 00:00:03.6283540 Calling 'NuGet'::'FindPackage' - name='Azure', requiredVersion='',minimumVersion='', maximumVersion='''.
DEBUG: 00:00:03.6283832 Iterating 'Azure'.
DEBUG: 00:00:03.6284863 There are '1' registered sources in 'NuGet' provider.
DEBUG: 00:00:03.6285134 Source 'http://www.powershellgallery.com/api/v2/' is not one of the registered sources in 'NuGet' provider.
DEBUG: 00:00:04.0032789 Source 'http://www.powershellgallery.com/api/v2/' is validated.
DEBUG: 00:00:04.0033488 Calling 'NuGetRequest'::'GetPackageById', 'Azure'.
DEBUG: 00:00:04.2605838 Calling 'HttpClientPackageRepository'::'FindPackagesById', 'Azure'.
DEBUG: 00:00:04.2606293 Calling 'NuGetClient'::'FindPackage'.
VERBOSE: Searching repository 'http://www.powershellgallery.com/api/v2/FindPackagesById()?id='Azure'' for ''.
DEBUG: 00:00:04.2607350 Downloading 'http://www.powershellgallery.com/api/v2/FindPackagesById()?id='Azure'&$skip=0&$top=40'.
DEBUG: 00:00:05.2207561 Completed downloading 'http://www.powershellgallery.com/api/v2/FindPackagesById()?id='Azure'&$skip=0&$top=40'.
DEBUG: 00:00:05.2353454 '10' packages recevied in the last request.
VERBOSE: Total package yield:'1' for the specified package 'Azure'.
DEBUG: 00:00:05.2385313 Completed iterating for 'Azure'.

Confirm
Are you sure you want to perform this action?
Performing the operation "Save Package" on target "E:\temp\Azure 1.3.1".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: 00:00:07.5606802 Calling 'NuGet'::'$aHR0cDovL3d3dy5wb3dlcnNoZWxsZ2FsbGVyeS5jb20vYXBpL3YyLw==\QXp1cmU=\MS4zLjE=\aHR0cDovL3d3dy5wb3dlcnNoZWxsZ2FsbGVyeS5jb20vYXBpL3YyLw==', 'E:\temp\Azure
 1.3.1'.
DEBUG: 00:00:07.5607176 Calling 'NuGetRequest'::'GetPackageByFastpath',
'$aHR0cDovL3d3dy5wb3dlcnNoZWxsZ2FsbGVyeS5jb20vYXBpL3YyLw==\QXp1cmU=\MS4zLjE=\aHR0cDovL3d3dy5wb3dlcnNoZWxsZ2FsbGVyeS5jb20vYXBpL3YyLw=='.
DEBUG: 00:00:07.5607606 Calling 'NuGetRequest'::'ResolvePackageSource', 'http://www.powershellgallery.com/api/v2/'.
DEBUG: 00:00:07.5608019 Calling 'NuGetRequest'::'FindRegisteredSource', 'http://www.powershellgallery.com/api/v2/'.
DEBUG: 00:00:07.5608450 Source 'http://www.powershellgallery.com/api/v2/' is not one of the registered sources in 'NuGet' provider.
DEBUG: 00:00:08.1958636 Calling 'HttpClientPackageRepository'::'FindPackage', 'Azure'.
DEBUG: 00:00:08.1959103 Calling 'NuGetClient'::'FindPackage'.
VERBOSE: Searching repository 'http://www.powershellgallery.com/api/v2/FindPackagesById()?id='Azure'' for ''.
DEBUG: 00:00:08.1959597 Downloading 'http://www.powershellgallery.com/api/v2/FindPackagesById()?id='Azure'&$skip=0&$top=40'.
DEBUG: 00:00:09.1109241 Completed downloading 'http://www.powershellgallery.com/api/v2/FindPackagesById()?id='Azure'&$skip=0&$top=40'.
DEBUG: 00:00:09.1261783 '10' packages recevied in the last request.
DEBUG: 00:00:09.1296880 Calling 'NuGetClient'::'GetPackageDependencies'.
DEBUG: 00:00:09.1306141 There are '1' registered sources in 'NuGet' provider.
DEBUG: 00:00:09.1306557 Source 'http://www.powershellgallery.com/api/v2/' is not one of the registered sources in 'NuGet' provider.
DEBUG: 00:00:09.3835585 Source 'http://www.powershellgallery.com/api/v2/' is validated.
DEBUG: 00:00:09.3836245 Calling 'NuGetRequest'::'GetPackageById', 'Azure.Storage'.
DEBUG: 00:00:09.6403160 Calling 'HttpClientPackageRepository'::'FindPackagesById', 'Azure.Storage'.
DEBUG: 00:00:09.6403886 Calling 'NuGetClient'::'FindPackage'.
VERBOSE: Searching repository 'http://www.powershellgallery.com/api/v2/FindPackagesById()?id='Azure.Storage'' for ''.
DEBUG: 00:00:09.6405013 Downloading 'http://www.powershellgallery.com/api/v2/FindPackagesById()?id='Azure.Storage'&$skip=0&$top=40'.
DEBUG: 00:00:09.7852142 Completed downloading 'http://www.powershellgallery.com/api/v2/FindPackagesById()?id='Azure.Storage'&$skip=0&$top=40'.
DEBUG: 00:00:09.7888559 '9' packages recevied in the last request.
DEBUG: 00:00:09.7899058 There are '1' registered sources in 'NuGet' provider.
DEBUG: 00:00:09.7899462 Source 'http://www.powershellgallery.com/api/v2/' is not one of the registered sources in 'NuGet' provider.
DEBUG: 00:00:10.0415460 Source 'http://www.powershellgallery.com/api/v2/' is validated.
DEBUG: 00:00:10.0416442 Calling 'NuGetRequest'::'GetPackageById', 'AzureRM.Profile'.
DEBUG: 00:00:10.2951008 Calling 'HttpClientPackageRepository'::'FindPackagesById', 'AzureRM.Profile'.
DEBUG: 00:00:10.2951481 Calling 'NuGetClient'::'FindPackage'.
VERBOSE: Searching repository 'http://www.powershellgallery.com/api/v2/FindPackagesById()?id='AzureRM.Profile'' for ''.
DEBUG: 00:00:10.2951987 Downloading 'http://www.powershellgallery.com/api/v2/FindPackagesById()?id='AzureRM.Profile'&$skip=0&$top=40'.
DEBUG: 00:00:10.4401967 Completed downloading 'http://www.powershellgallery.com/api/v2/FindPackagesById()?id='AzureRM.Profile'&$skip=0&$top=40'.
DEBUG: 00:00:10.4412761 '9' packages recevied in the last request.
DEBUG: 00:00:10.4417485 Returning the call 'NuGetClient'::'GetPackageDependencies'.
VERBOSE: Skipping Downloaded Package 'AzureRM.profile'.
VERBOSE: DownloadPackage' - name='Azure.Storage', version='1.1.0',destination='E:\temp\Azure 1.3.1\Azure.Storage.1.1.0.nupkg',
uri='http://www.powershellgallery.com/api/v2/package/Azure.Storage/1.1.0'
VERBOSE: Downloading 'http://www.powershellgallery.com/api/v2/package/Azure.Storage/1.1.0'.
VERBOSE: Completed downloading 'http://www.powershellgallery.com/api/v2/package/Azure.Storage/1.1.0'.
VERBOSE: Completed downloading 'Azure.Storage'.
VERBOSE: Package 'Azure.Storage' is downloaded.

Name                           Version          Source                         Summary
----                           -------          ------                         -------
AzureRM.profile                1.0.6            http://www.powershellgaller... Microsoft Azure PowerShell - Profile credential management cmdlets for Azure Resource Manager
VERBOSE: DownloadPackage' - name='Azure', version='1.3.1',destination='E:\temp\Azure 1.3.1\Azure.1.3.1.nupkg', uri='http://www.powershellgallery.com/api/v2/package/Azure/1.3.1'
VERBOSE: Downloading 'http://www.powershellgallery.com/api/v2/package/Azure/1.3.1'.
DEBUG: 00:01:58.9203789 System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException:
 A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.PackageManagement.NuGetProvider.PathUtility.GetHttpResponse(HttpClient httpClient, String query, Request request)
   at Microsoft.PackageManagement.NuGetProvider.NuGetClient.<DownloadDataToFileAsync>d__f.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.PackageManagement.NuGetProvider.NuGetClient.DownloadPackage(String packageName, String version, String destination, String queryUrl, NuGetRequest request, PackageSource
pkgSource)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.PackageManagement.NuGetProvider.PathUtility.GetHttpResponse(HttpClient httpClient, String query, Request request)
   at Microsoft.PackageManagement.NuGetProvider.NuGetClient.<DownloadDataToFileAsync>d__f.MoveNext()
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
<---
WARNING: Package 'Azure' failed to download.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A

**Comment by eosfor** [comment]
Here is what i see https://www.youtube.com/watch?v=uBA7TZbUhuQ. At some point it freezes and then fails

**Comment by quoctruong** [comment]
The issue seems to be because of Internet connection and timeout. We are publishing a newer version of NuGetProvider that will handle downloading better. I'll update the thread once it is published so you can try it out!

**Comment by eosfor** [comment]
Any news, sorry?

**Comment by quoctruong** [comment]
Hi @eosfor, we are currently testing before publishing the newer version of NuGetProvider. I can send you a private drop if you want to try it out before it is published.

**Comment by eosfor** [comment]
Yes please

**Comment by quoctruong** [comment]
HI @eosfor, can you provide me with an email address so I can send you the drop? Thanks!

**Comment by eosfor** [comment]
eosfor@gmail.com

**Comment by eosfor** [comment]
It worked

**Comment by quoctruong** [comment]
Glad to hear that it's working!
