### ISSUE TITLE
chocolatey: can't install cygwin

### ISSUE THREAD

**Issue by sergey-s-betke** [OneGet/oneget#177]
Import-Module `
            -Name PackageManagement `
        ;
        Install-PackageProvider `
            -Name NuGet `
            -Force `
        ;
        Register-PackageSource `
            -Name NuGet `
            -ProviderName NuGet `
            -Location 'http://packages.nuget.org/api/v2/' `
            -Trusted `
            -Force `
        ;
        Install-PackageProvider `
            -Name Chocolatey `
            -Force `
        ;
        Import-PackageProvider `
            -Name Chocolatey `
            -Force `
        ;
        Register-PackageSource `
            -Name chocolatey `
            -ProviderName Chocolatey `
            -Location 'http://chocolatey.org/api/v2/' `
            -Trusted `
            -Force `
        ;
        Install-Package `
            -Name 'cygwin' `
            -Source chocolatey `
            -Verbose `
            -ForceBootstrap `
            -Force `
        ;

produced error. But `choco install Cygwin` - install `Cygwin` successfully...

**Comment by quoctruong** [comment]
Hi @sergey-s-betke , can I ask what the ExecutionPolicy on your machine is? You can see this with Get-ExecutionPolicy

**Comment by sergey-s-betke** [comment]
RemoteSigned

**Comment by quoctruong** [comment]
I know there is an issue with chocolatey where you have to loosen the ExecutionPolicy before it can run successfully. Have you tried with other ExecutionPolicy?
