### ISSUE TITLE
(CP) Cmdlets to download/upload packages without installing

### ISSUE THREAD

**Issue by xumins** [OneGet/oneget#18]
https://oneget.codeplex.com/workitem/7
Provide a command to download (but not install) a package via OneGet and another to upload a package to a repository. This is useful to be able to copy a package from an untrusted public repository, validate it doesn't do anything harmful, and then copy it to a trusted local repository.

comments

bherila wrote Apr 9 at 9:14 PM [x] 
◾Download (but not install) is in our roadmap 
◾Upload is something we are not committing to right now, but we are closely monitoring the community feedback and may consider adding in a future release.

**Comment by quoctruong** [comment]
We have the cmdlet Save-Package for downloading package
