### ISSUE TITLE
Cannot pull nuget.exe with firewall-side SSL decryption

### ISSUE THREAD

**Issue by megamorf** [OneGet/oneget#180]
Hey guys,

@KrishnaV-MSFT pointed me here.

Problem:
Can't pull Nuget on WMF5 with firewall-side SSL decryption. Please share domains/IP ranges that PowerShellGet uses to get Nuget. Due to that it never installs the PackageProvider which is why I don't have any PackageSources either.

Environment:
* German Win7 SP1
* PSv5 (originally PS v2 -> upgraded with WMF4 RTM -> upgraded with WMF5 RTM (fixed February '16 version))
* PaloAlto Firewall doing SSL decryption for all clients in our company (basically MITM which requires a certificate in the the local machine's trusted root cert store)
* no proxy

**Comment by quoctruong** [comment]
Hi @megamorf, can you provide the result of running "Find-PackageProvider nuget -verbose -Debug"?

**Comment by megamorf** [comment]
@quoctruong Thanks for the command. It not only gave me the domains required to get the nuget binaries but it also helped me find the root cause: old internet explorer maintenance GPO settings that made PowerShell use a proxy even though we deconfigured proxies 3 months ago.

Thanks again :-)
