### ISSUE TITLE
Unable to find module providers (PowerShellGet).

### ISSUE THREAD

**Issue by murcury** [OneGet/oneget#183]
#### System Info:
```
PS C:\WINDOWS\system32> [environment]::OSVersion.Version
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      10586  0
```

```
PS C:\WINDOWS\system32> $PSVersionTable.PSVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10586  122
```

#### Error:
```
PS C:\WINDOWS\system32> Get-PSRepository
PackageManagement\Get-PackageSource : Unable to find module providers (PowerShellGet).
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:3544 char:31
+ ... ckageSources = PackageManagement\Get-PackageSource @PSBoundParameters
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power...etPackageSource:GetPackageSource) [Get-PackageSource
   ], Exception
    + FullyQualifiedErrorId : UnknownProviders,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPackageSource
```

#### The below returns nothing:
```
PS C:\WINDOWS\system32> Get-PackageProvider -ListAvailable
PS C:\WINDOWS\system32>
```

**Comment by murcury** [comment]
Looks like I solved the issue. I installed Chocolatey by using the CMD.exe method.

I ran CMD.exe as an administrator and ran the following command:

```
@powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin
```

Now I have a PS Repository: PS C:\WINDOWS\system32> Get-PSRepository

```
Name                      PackageManagementProvider InstallationPolicy   SourceLocation
----                      ------------------------- ------------------   --------------
PSGallery                 NuGet                     Untrusted            https://www.powershellgallery.com/api/v2/
```

I'm guessing something during the install of Chocolatey, repaired whatever was broken.

**Comment by dermeister0** [comment]
The same issue for me on clean Windows Server 2016 virtual machine.

**Comment by msvaillant** [comment]
I have no luck with this problem
``` powershell
PS C:\Windows\system32> Get-PSRepository
WARNING: Unable to find module repositories.
```

``` powershell
PS C:\Windows\system32> [environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0
````

``` powershell
PS C:\Windows\system32> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  693
```

``` powershell
PS C:\Windows\system32> Get-PackageProvider -ListAvailable

Name                     Version          DynamicOptions
----                     -------          --------------
Chocolatey               2.8.5.130        SkipDependencies, ContinueOnFailure, ExcludeVersion, ForceX86, PackageSave...
msi                      3.0.0.0          AdditionalArguments
msu                      3.0.0.0
NuGet                    2.8.5.208        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag...
PowerShellGet            1.0.0.1          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, ...
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent
```

I tried
``` powershell
PS C:\Windows\system32> Register-PSRepository -Default -Verbose
VERBOSE: Performing the operation "Register Module Repository." on target "Module Repository 'PSGallery' () in provider 'PowerShellGet'.".
```

``` powershell
Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
```

but get-psrepository stays empty - can you help me with this strange situation?

**Comment by dermeister0** [comment]
Try following command:

```
Register-PSRepository -Name PSGallery -SourceLocation https://www.powershellgallery.com/api/v2/ -PackageManagementProvider NuGet -PublishLocation https://www.powershellgallery.com/api/v2/package/ -ScriptSourceLocation https://www.powershellgallery.com/api/v2/items/psscript/ -ScriptPublishLocation https://www.powershellgallery.com/api/v2/package/
```

**Comment by msvaillant** [comment]
@dermeister0 

``` powershell
PS C:\Windows\system32> Register-PSRepository -Name PSGallery -SourceLocation https://www.powershellgallery.com/api/v2/
-PackageManagementProvider NuGet -PublishLocation https://www.powershellgallery.com/api/v2/package/ -ScriptSourceLocatio
n https://www.powershellgallery.com/api/v2/items/psscript/ -ScriptPublishLocation https://www.powershellgallery.com/api/
v2/package/
Register-PSRepository : Use 'Register-PSRepository -Default' to register the PSGallery repository.
At line:1 char:1
+ Register-PSRepository -Name PSGallery -SourceLocation https://www.pow ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (PSGallery:String) [Register-PSRepository], ArgumentException
    + FullyQualifiedErrorId : UseDefaultParameterSetOnRegisterPSRepository,Register-PSRepository
```

**Comment by samkh79** [comment]
@msvalliant did you find and solution to your problem above? I am coming across the exact same error.

**Comment by msvaillant** [comment]
@samkh79 I have contacted network admins to help me solve this problem, and they did it somehow. As I understand it is problem with whitelist/blacklist of host in firewall settings

**Comment by efav** [comment]
@msvaillant Thank you for the post. It saves me a ton of time. I'll abandon trying to use the psgallery from work.

**Comment by nbuuck** [comment]
I began encountering problems with executing `Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Verbose -Force` after SSL/TLS hardening was applied to the server where the command was executing. I had to revert the protocol and ciphers (HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL) and cipher suite (HKLM\SYSTEM\CurrentControlSet\Control\Cryptography) preferences to default values in order for `Install-PackageProvider` and the underlying libraries to be able to connect to www.powershellgallery.com.

Before SSL/TLS hardening was backed out, I saw Event ID 36871 in the System log each time I tried to install the NuGet provider. The event text was:
> A fatal error occurred while creating a TLS client credential. The internal error state is 10013.

**Comment by decmaxn** [comment]
I am getting the same problem on a Windows Server 2016 version 1607 Build 14393.447 installation with GUI, but it's not happening on the installation without GUI. $PSVersionTable return exactly same version on both installation.

**Comment by samkh79** [comment]
I also have the network team enable internet access temporarily on the servers to make it to work.

**Comment by nathanmcnulty** [comment]
For those who have performed protocol/cipher suite hardening, you can use this on a per-session basis to tell the client to use TLS 1.2 instead:

` [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`

Just run that right before your Get-PSRepository or Install-Module ;)

**Comment by JrEach25** [comment]
What worked for me was to disable FIPS in regedit and reboot.  Then run [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12.  Finally, run Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force.

**Comment by ChrisKapend** [comment]
> 
> 
> What worked for me was to disable FIPS in regedit and reboot. Then run [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12. Finally, run Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force.

Hey @JrEach25 don't know if you'll ever read this but you saved me !!! spend about two hours trying to get this sorted, I'm not sure if the issue is related to windows virtual machines ? or some update ?

**Comment by alerickson** [comment]
Hi @ChrisKapend are you still having this issue with the latest version of PackageMangagement?

**Comment by ChrisKapend** [comment]
> Hi @ChrisKapend are you still having this issue with the latest version of PackageManagement? If so what command are you running?

Hi @alerickson  thanks for reaching out, after updating NuGet version 3.0.0.1 the error disappears

**Comment by rdoloto** [comment]
I know this is bit old but you need to set following  **Enable-TlsCipherSuite -Name "TLS_DHE_DSS_WITH_AES_256_CBC_SHA" -Position 0** if you are restricting ciphers in enviorment
