### ISSUE TITLE
Wrong NuGet Provider Version is sometimes loaded.

### ISSUE THREAD

**Issue by gerane** [OneGet/oneget#184]
OS: Windows 10

In some cases, I am seeing the wrong package provider version being loaded. I have NuGet '2.8.5.205' installed, but sometimes I get prompted that PowerShellGet needs to install NuGet '2.8.5.201' or newer. When I run Get-PackageProvider I see that '2.8.5.127' is the version loaded even though I have 3 newer versions installed.

**Comment by quoctruong** [comment]
Hi @gerane, if you check under "C:\Program Files\PackageManagement\ProviderAssemblies", do you see a nuget-anycpu.exe? If so, please remove that file and try again.

**Comment by jianyunt** [comment]
Thanks for reporting it. The fix is in the TP5.
