### ISSUE TITLE
Update-ScriptInfo requires non-mandatory parameters

### ISSUE THREAD

**Issue by DouglasPlumley** [OneGet/oneget#185]
PS version 5.0.10586.122, PowerShellGet version 1.0.0.1.

Whenever I try to update the script information in a ps1 file that already has the information I'm unable to proceed if I don't provide arguments to non-mandatory parameters.

```
[ValidateNotNullOrEmpty()]
[string]
$Copyright,

[Parameter()]
[ValidateNotNullOrEmpty()]
[String[]]
$ExternalModuleDependencies

```

This appears to be happening for all parameters, I've highlighted Copyright and ExternalModuleDependencies.

```
Update-ScriptFileInfo -Path "c:\test.ps1 -Version 1.0.0.0"

The variable cannot be validated because the value  is not a valid value for the Copyright variable.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:4313 char:13
+             $Copyright = $psscriptInfo.Copyright
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ValidationMetadataException
    + FullyQualifiedErrorId : ValidateSetFailure

The variable cannot be validated because the value $null is not a valid value for the ExternalModuleDependencies variable.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:4323 char:13
+             $ExternalModuleDependencies = $psscriptInfo.ExternalModul ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ValidationMetadataException
    + FullyQualifiedErrorId : ValidateSetFailure
```

I believe you are supposed to be able to provide no input and Update-ScriptInfo should maintain the current value even if it is "" or $null.

**Comment by bmanikm** [comment]
@DouglasPlumley, Yes, this is a known issue and got fixed in the newer releases of Windows.

**Comment by DouglasPlumley** [comment]
@bmanikm I'm in Win 10 Version 1511 Build 10586.420 but don't have the fix, do you know at what build number this started being included?

Thanks!

**Comment by bmanikm** [comment]
@DouglasPlumley, The fix is available in Windows Server 2016 Technical Preview 5 release.
We are also planning to release the latest version of PowerShellGet module to the PowerShellGallery.com.

**Comment by jianyunt** [comment]
This issue was moved to PowerShell/PowerShellGet#48
