### ISSUE TITLE
Find-Package fails to find a package when it is found on another machine

### ISSUE THREAD

**Issue by eosfor** [OneGet/oneget#187]
PS D:\temp> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS D:\temp> Find-Package SharpZipLib -Verbose -Debug
DEBUG: 00:00:00.0000016 Calling 'msu::GetDynamicOptions' 'Provider'

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: 00:00:00.0031653 Calling 'msu::GetDynamicOptions' 'Source'
DEBUG: 00:00:00.0060721 Calling 'msu::GetDynamicOptions' 'Package'
DEBUG: 00:00:00.0097271 Calling 'Programs::GetDynamicOptions' 'Provider'
DEBUG: 00:00:00.0130575 Calling 'Programs::GetDynamicOptions' 'Source'
DEBUG: 00:00:00.0159811 Calling 'Programs::GetDynamicOptions' 'Package'
DEBUG: 00:00:00.0188293 Calling 'msi::GetDynamicOptions' 'Provider'
DEBUG: 00:00:00.0218499 Calling 'msi::GetDynamicOptions' 'Source'
DEBUG: 00:00:00.0254870 Calling 'msi::GetDynamicOptions' 'Package'
DEBUG: 00:00:00.0485635 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0486004 Verbose: True
DEBUG: 00:00:00.0486248 Debug: True
DEBUG: 00:00:00.0486479 Name: SharpZipLib
DEBUG: 00:00:00.0495421 INVOKING PowerShell Fn Get-DynamicOptions with args Provider that has length 1
DEBUG: 00:00:00.0502981 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0521819 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0551262 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0551599 Verbose: True
DEBUG: 00:00:00.0551844 Debug: True
DEBUG: 00:00:00.0552070 Name: SharpZipLib
DEBUG: 00:00:00.0559339 INVOKING PowerShell Fn Get-DynamicOptions with args Source that has length 1
DEBUG: 00:00:00.0566221 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0597635 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0627160 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0627496 Verbose: True
DEBUG: 00:00:00.0627736 Debug: True
DEBUG: 00:00:00.0627962 Name: SharpZipLib
DEBUG: 00:00:00.0634974 INVOKING PowerShell Fn Get-DynamicOptions with args Package that has length 1
DEBUG: 00:00:00.0644794 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.1053989 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:02.2974181 Calling SearchForPackages. Name='SharpZipLib'
VERBOSE: Using the provider 'msu' for searching packages.
DEBUG: 00:00:02.2988632 PackageProvider::FindPackage with name SharpZipLib
VERBOSE: Using the provider 'Programs' for searching packages.
DEBUG: 00:00:02.3092497 PackageProvider::FindPackage with name SharpZipLib
VERBOSE: Using the provider 'msi' for searching packages.
DEBUG: 00:00:02.3263101 PackageProvider::FindPackage with name SharpZipLib
VERBOSE: Using the provider 'NuGet' for searching packages.
DEBUG: 00:00:02.3408928 PackageProvider::FindPackage with name SharpZipLib
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
DEBUG: 00:00:02.3422995 PackageProvider::FindPackage with name SharpZipLib
DEBUG: 00:00:02.3446742 Calling 'NuGet'::'FindPackage' - name='SharpZipLib', requiredVersion='',minimumVersion='',
maximumVersion='''.
DEBUG: 00:00:02.3447435 Iterating 'SharpZipLib'.
DEBUG: 00:00:02.3449649 There are '0' registered sources in 'NuGet' provider.
VERBOSE: Total package yield:'0' for the specified package 'SharpZipLib'.
DEBUG: 00:00:02.3451366 Completed iterating for 'SharpZipLib'.
DEBUG: 00:00:02.3612408 Calling SearchForPackages After Select 5
DEBUG: 00:00:02.3634122 Calling New() : MethodName = 'FindPackage'
DEBUG: 00:00:02.3634473 Verbose: True
DEBUG: 00:00:02.3634730 Debug: True
DEBUG: 00:00:02.3634969 Name: SharpZipLib
DEBUG: 00:00:02.3663167 INVOKING PowerShell Fn Find-Package with args System.String[], , ,  that has length 4
DEBUG: 00:00:02.3747456 In PowerShellGet Provider - 'Find-Package'.
DEBUG: 00:00:02.3751981 OPTION: Verbose => True
DEBUG: 00:00:02.3753942 OPTION: Debug => True
DEBUG: 00:00:02.3755797 OPTION: Name => SharpZipLib
VERBOSE: The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2/' and PackageManagementProvider is
'NuGet'.
DEBUG: 00:00:02.3806882 PackageProvider::FindPackage with name SharpZipLib
DEBUG: 00:00:02.3917038 Calling 'NuGet'::'FindPackage' - name='SharpZipLib', requiredVersion='',minimumVersion='',
maximumVersion='''.
DEBUG: 00:00:02.3917766 Iterating 'SharpZipLib'.
DEBUG: 00:00:02.3921733 There are '0' registered sources in 'NuGet' provider.
DEBUG: 00:00:02.3922231 Source 'https://www.powershellgallery.com/api/v2/' is not one of the registered sources in
'NuGet' provider.
DEBUG: 00:00:03.6317097 Source 'https://www.powershellgallery.com/api/v2/' is validated.
DEBUG: 00:00:03.6318146 Calling 'NuGetRequest'::'GetPackageById', 'SharpZipLib'.
DEBUG: 00:00:03.7233149 Calling 'HttpClientPackageRepository'::'FindPackagesById', 'SharpZipLib'.
DEBUG: 00:00:03.7234001 Calling 'NuGetClient'::'FindPackage'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='SharpZipLib'' for ''.
DEBUG: 00:00:03.7235264 Downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='SharpZipLib'&$skip=0&$top=40'.
DEBUG: 00:00:03.9044272 Completed downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='SharpZipLib'&$skip=0&$top=40'.
DEBUG: 00:00:03.9046271 '0' packages recevied in the last request.
VERBOSE: Total package yield:'0' for the specified package 'SharpZipLib'.
DEBUG: 00:00:03.9047567 Completed iterating for 'SharpZipLib'.
DEBUG: 00:00:03.9051340 PowerShell Script 'PSModule' Function 'Find-Package' returns null.
DEBUG: 00:00:03.9077264 Done calling powershell «Find-Package» «PSModule»
DEBUG: 00:00:03.9124568 unmatched package name='SharpZipLib'

Confirm
No match was found for the specified search criteria and package name 'SharpZipLib'.
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
Find-Package : No match was found for the specified search criteria and package name 'SharpZipLib'.
At line:1 char:1
+ Find-Package SharpZipLib -Verbose -Debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ets.FindPackage:FindPackage) [Find-Package], Exceptio
   n
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.FindPackage

PS D:\temp> Get-PackageProvider

Name                     Version          DynamicOptions
----                     -------          --------------
msi                      3.0.0.0          AdditionalArguments
msu                      3.0.0.0
NuGet                    2.8.5.205        Destination, ExcludeVersion, Scope, Headers, FilterOnTag, Contains, AllowP...
PowerShellGet            1.0.0.1          PackageManagementProvider, Type, Scope, InstallUpdate, PackageManagementPr...
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent

**Comment by jianyunt** [comment]
Can you try 
Find-Package SharpZipLib -Verbose -Source http://www.nuget.org/api/v2/

if the above works, please try the following to see if NuGet exists and source is registered.
   Get-packageprovider
   Get-PackageSource
  
If the source does not get registered, you can register the package source by
Register-PackageSource -Name nuget.org -Location http://www.nuget.org/api/v2/ -ProviderName nuget

Find-Package SharpZipLib -Verbose 

or simply pass the source in the find-package cmdlet.

**Comment by eosfor** [comment]
I'll try and let you know, thank you
