### ISSUE TITLE
OneGet download link is broken

### ISSUE THREAD

**Issue by jondavis-ineight** [OneGet/oneget#188]
The download link for the latest OneGet in the README.md file (http://www.microsoft.com/en-us/download/details.aspx?id=48729) is a bad link. If OneGet has been abandoned or renamed, this repository needs to be updated to *say so*.

My PSE isn't starting up correctly due to a bad Module Browser extension module install from months ago, I Googled and found that I probably need to update OneGet, I came here and followed the "download latest" link, and I end up with a 404. True story.

**Comment by jianyunt** [comment]
@jondavis-ineight, thank you for reporting it.  The link is fixed now.
Regarding the Module Browser issue, it's known. We are contacting that team for the fix.  The issue has been tracking in https://github.com/OneGet/oneget/issues/166.

**Comment by jianyunt** [comment]
let's use https://github.com/OneGet/oneget/issues/166 for tracking module browser issue. The link is fixed now.
