### ISSUE TITLE
Find-Module and Install-Module fail if there are dependencies in manifest

### ISSUE THREAD

**Issue by slimracing** [OneGet/oneget#190]
Attempting to Find or Install a module on a private NuGet repository fails if the feed returns items in the dependencies element. This element is populated if there are values in the 'NestedModules' module manifest section.

**Comment by bmanikm** [comment]
@slimracing, could you please provide more details to repro this issue? If your private gallery has the dependencies, Install-Module will install them too. How did you populate your private repositories? You should use Publish-Module cmdlet to publish the modules to your private repository.

**Comment by slimracing** [comment]
Both modules were published via Publish-Module to a local Nexus artifact repository. The dependency is available and can be installed separately via Install-Module and Find-Module also returns results for it. My custom module which depends on it can be found and installed just fine as long as I comment out the 'NestedModules' property of the module manifest before publishing with Publish-Module. Locally the modules function as expected if NestedModules is used. The custom module will auto-load the nested module as needed and unload the nested module when the custom module is removed.

After manually inspecting the output of the call to the nuget service, ../FindPackagesById(), the only difference in the output returned is a value for the /feed/entry/properties/dependencies element. When it works the value of this element is <d:Dependencies m:null="true"/>, when it does not work the value is <d:Dependencies>ModuleName:null</d:Dependencies>

**Comment by bmanikm** [comment]
@slimracing , from the above provided details, it looks like the issue is with the Nexus artifact repository implementation. Ensure that Nexus artifact repository returns the dependency metadata similar to that from a NuGet based repository.

Current:
 <d:Dependencies>ModuleName:null</d:Dependencies> 

Expected:
 <d:Dependencies>ModuleName::</d:Dependencies>

**Comment by slimracing** [comment]
I will look into that and test with another nuGet repository. Can you please fix your comment markup so I can be sure of what should be returned?

**Comment by slimracing** [comment]
I am unable to reproduce this using the Nuget.Server application available from nuget.org. When publishing the same module and manifest to that server, the dependencies element is empty: `<d:Dependencies></d:Dependencies>`. Unfortunately, while this allows the module with a configured NestedModules section to be installed, it obviously does not fetch the dependency at install time. As the original scope of this issue appears to be a Nexus issue, this can be closed.

**Comment by slimracing** [comment]
Solved the issue by explicitly setting a module version in the Powershell manifest using a hash table per documentation here: https://technet.microsoft.com/en-us/library/hh849709.aspx

That resulted in a well formed dependencies element and the Install-Module command worked as expected, installing both the main module and its dependency.
