### ISSUE TITLE
Installer won't build

### ISSUE THREAD

**Issue by wendellh3** [OneGet/oneget#191]
When trying to build the WiX projects:
`error LGHT0094: Unresolved reference to symbol 'Binary:WixCA' in section 'Product:*'. [...\oneget\Package\Msi\msi.wixproj]`
referring to this line in Package.wxs
`<CustomAction Id="RunScript" BinaryKey="WixCA" DllEntry="CAQuietExec64" Execute="deferred" Return="ignore" Impersonate="no" />`
running WiX 3.9
There seems to be a few problems with paths (light.exe can't find files), but I'm new to WiX. Are there instructions you can provide for building an MSI/Installer?

**Comment by rockobonaparte** [comment]
You need to add WixUtilExtension.dll as a reference to the WiX project:
http://wixtoolset.org/documentation/manual/v3/customactions/qtexec.html

That won't completely save you though. I got past that and then couldn't get the installer to do anything without getting real ugly. I'm about to open an issue for creating an installer for Nano Server.
