### ISSUE TITLE
Publish-Module and Authenticated Feeds

### ISSUE THREAD

**Issue by whatatripp** [OneGet/oneget#192]
Our customers seem to have a lot of issues with Publish-Module when they use authenticated feeds.

Windows Integrated Authentication doesn't work at all (the 401/challenge isn't recognized), and trying to use ProGet's "name:pass" convention as the API key for doesn't work, because OneGet/PowerShellGet/something is encoding the ":" and non-alpha characters incorrectly.

Is this, or can this be supported? Currently, it's entirely unusable with authenticated feeds.

Here's an example thread from our support forums: [http://inedo.com/support/questions/4964](http://inedo.com/support/questions/4964)

**Comment by jianyunt** [comment]
This issue was moved to PowerShell/PowerShellGet#47
