### ISSUE TITLE
Proposition: add a well-defined folder to PATH, so executables can be sym-linked from it

### ISSUE THREAD

**Issue by vors** [OneGet/oneget#193]
I was talking with @bmanikm about installing `cmake` thru `Install-Package`. One of the user-experience problems (how I see it) is the fact that installed tools are not immediately accessible from command line.

I.e. I install `cmake` with something like

```
install-package -name CMake -RequiredVersion 3.5.2 -Provider NuGet -Source https://www.nuget.org/api/v2
```

Now to run it, I can ether use full path `& 'C:\Program Files\NuGet\Packages\CMake.3.5.2\bin\cmake'`, or manipulate my `PATH` env variable.

And this comes to a broad problem:
- you don't want to put too much garbage in PATH
- at the same time you want your tools in your PATH

On Linux this problem is solved on the system-level. There are well defined locations (i.e. `/usr/bin`), where programs can manifest them-selves.

Chocolatey (as far as I understand) solves this problem with it's own well-defined folder, where you can put `.cmd` wrappers or symlink files. That gives `choco` ability to instantly add new commands to the command line and provides a great user experience.

So the proposition / questions is: can oneget adopt similar (or maybe different) technique to provide a better UX for command-line tools?

**Comment by jianyunt** [comment]
good idea. we need to find way to keep tracking the path of where each package installed, and then add the common folder to the $env:path.

**Comment by jianyunt** [comment]
We track this feature in our backlog for NuGet provider.

**Comment by Jaykul** [comment]
This needs to be solved by a **provider** that is *designed* for installing **applications**.  For instance, with the `Chocolatey` provider, adding the application to your path would be an _option_ (you'd probably only want to do that for CLI apps and tools, most things will be launched from the start menu).

Anyway. Please **DO NOT** add a feature like that to the NuGet provider ... which is primarily for installing development packages.

**Comment by bherila** [comment]
Agreed with @Jaykul (hello again @jianyunt 😄 ) 

This problem should (I think) be solved on Windows with the "App Paths" reg key. This allows (at least) Explorer to resolve .exe files by name without having to add them to the PATH. This is why you can go to Start > Run and type OUTLOOK and have Outlook.exe started up from its Program Files location.

Reference: https://msdn.microsoft.com/en-us/library/windows/desktop/ee872121(v=vs.85).aspx

**Comment by jianyunt** [comment]
I see. Thanks @bherila and @Jaykul for your design suggestions . This item is still in our backlog.

**Comment by jianyunt** [comment]
Since Install-Package already supports -Destination parameter, we decided not to support this feature.

**Comment by JKeithB** [comment]
After triage and review, we have marked this as Won't Fix. The right way to handle this is for the script to expand the well-known path item before passing it to install-package.
