### ISSUE TITLE
Link in "Get Started" doesn't work

### ISSUE THREAD

**Issue by Vixine** [OneGet/oneget#198]
https://github.com/OneGet/oneget#get-started
 At this line: 

> Learn how to use the powershell cmdlets, try some samples, or read our MSDN Technet docs

"try some samples" is a dead link: https://msdn.microsoft.com/en-us/powershell/wmf/oneget_cmdlets

it's also linked to over here: https://github.com/OneGet/oneget/wiki/cmdlets under 
>Also see more references:

**Comment by jianyunt** [comment]
Thanks for reporting it. I fixed the link in the OneGet.org wiki.
@juanpablojofre, what happened to msdn?

**Comment by jianyunt** [comment]
fixed link
