### ISSUE TITLE
Need instructions for the WiX build process

### ISSUE THREAD

**Issue by rockobonaparte** [OneGet/oneget#205]
I have been trying to update the PackageManager in a TP5 Nano Server system because I need that new post-TP5 Proxy support. This has been a series of misadventures because I cannot get a recursive file copy to work right, nor can I decompress a zip file on the machine to get all the build output there.

So let's be clear that I did manage to get it all to build, but the WiX project was not in the solution. I eventually found it, but it seemed out-of-touch. It didn't reference the build output at all; it just assumed to be running in the same directory as the project. It also relied on some Dlls that are neither part of the build nor on my machine at the time.

Can you post some instructions to go with the build process on how to create that installer?

For what it's worth, is the installer compatible with Nano Server?

**Comment by jianyunt** [comment]
@rockobonaparte we do not plan to support WiX build. We are thinking to publish the OneGet and NuGet as one package to PowerShellGallery.com.  Stay tuned for that.

Also we are currently working on moving OneGet out of [powershell  repo](https://github.com/PowerShell/PowerShell/).  But still will be a part of PowerShellCore  as cross repo dependency during the build time. With that said, you can update OneGet bits with PowerShellCore on nano. It's an alpha version now. Later on once PowerShellCore is stabilized, you can install it on Nano server to try the latest builds.

**Comment by rockobonaparte** [comment]
I was following the build process and it mentioned having WiX if we intended to build the installer. What is the proper process for creating an installer without WiX?

**Comment by jianyunt** [comment]
Add @raghushantha for a process to build a package.

**Comment by jianyunt** [comment]
@rockobonaparte  we are using dotnet build now. You can follow the steps below to generate binaries, then you can package them using nuget.exe or simply zip it.

git clone --recursive https://github.com/OneGet/oneget.git
cd src
./bootstrap.ps1
..\build.ps1 net451 Release
