### ISSUE TITLE
PSGet setting DotNetFrameworkVersion results in malformed package

### ISSUE THREAD

**Issue by Daniel-Guenter** [OneGet/oneget#211]
Setting the variable DotNetFrameworkVersion in the .psd1 file of a powershell package results in a malformed package.  Publish-Module will succeed but Save-Module or Install-Module errors out.

> PS D:\Memx\AX\Tools\Projects\MemX.PS\MemX.PS.Core.Module\bin\Debug> Save-Module
-Name MemX.PS.Core.Module -Path D:\Tmp
PackageManagement\Install-Package : Cannot bind argument to parameter
'PSModuleInfo' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\PSGet.psm1:827
char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power....InstallPackage:
   InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,G
   et-ExternalModuleDependencies,Microsoft.PowerShell.PackageManagement.Cmdle
  ts.InstallPackage

Or...

> PS D:\Memx\AX\Tools\Projects\MemX.PS\MemX.PS.Core.Module\bin\Debug> Save-Module
-Name MemX.PS.Core.Module -Path D:\Tmp
PackageManagement\Install-Package : Cannot bind argument to parameter
'PSModuleInfo' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\PSGet.psm1:827
char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power....InstallPackage:
   InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,G
   et-ExternalModuleDependencies,Microsoft.PowerShell.PackageManagement.Cmdle
  ts.InstallPackage

It seems that the nuget package extraction is resulting in a lib/net4.5/dll folder structure without any .psd1 or .psm1  files.  The installer then errors because it can't find the .psd1 file.  Simply removing the DotNetFrameworkVersion directive from the .psd1 file solves the issue.

**Comment by bmanikm** [comment]
@Daniel-Guenter Could you please provide the complete repro steps and module contents? It looks like you are using very old version of PowerShellGet module. Ensure that Test-ModuleManifest works fine with your module contents too.

**Comment by Daniel-Guenter** [comment]
It looks like updating PowerShellGet solved this issue.  Thanks for pointing me in the right direction.
