### ISSUE TITLE
Disable older version of NuGet provider to be installed or loaded on PowerShell Core from repo. 

### ISSUE THREAD

**Issue by bmanikm** [OneGet/oneget#233]
_From @jianyunt on July 13, 2016 20:48_

As NuGet provider is a part of PowerShell Core now, it no longer requires to be bootstrapped. However, we need to disable any older version of NuGet provider to be installed or used on Core because they simply won't work on PowerShell Core alpha version..
## Steps to reproduce

find-packageprovider
install-packageprovider -name NuGet -version 2.8.5.205 -force
install-module xjea
## Expected behavior

Error out if people are trying load any older version of NuGet provider
## Actual behavior

not sure yet
## Environment data

PowerShell

_Copied from original issue: PowerShell/PowerShell#1355_
https://github.com/PowerShell/PowerShellGet/issues/27

**Comment by jianyunt** [comment]
@SteveL-MSFT,  These are PowerShell Core build/setup issue, why moved here?

**Comment by SteveL-MSFT** [comment]
@jianyunt we bulk moved a bunch of issues we thought belong in their own repos.  are you saying the fix is in PowerShell Core?

**Comment by jianyunt** [comment]
@SteveL-MSFT, Yes. The fix should be in PowerShellCore.

**Comment by SteveL-MSFT** [comment]
I reopened the original, you can close this one

**Comment by jianyunt** [comment]
ok. thx
