### ISSUE TITLE
Add -PackageSaveMode tag to Install-Package in the NuGet PackageManagement Provider

### ISSUE THREAD

**Issue by jeopal** [OneGet/oneget#234]
We are migrating our infrastructure from NuGet.exe to the NuGet PackageManagement Provider. "nuget install" had the option to install the NuGet and retain the nuspec rather than the nupkg in the installed NuGet (The command was this: nuget install <nugetName> -packagesavemode "nuspec"). We cannot switch our install commands to Install-Package until it is updated to mimic this functionality because doing so would greatly increase the size of our product. We have a large number of NuGets in our product, and retaining multiple copies of the nupkgs is a huge increase in size.

**Comment by jianyunt** [comment]
Save-Package -path will save the nupkg to save space.
Install-package does keep the nupkg.
We need more data if go for fix.
