### ISSUE TITLE
update links in readme.md

### ISSUE THREAD

**Issue by nschley** [OneGet/oneget#236]
The following links need to be updated at the top of the "Building the code" section: 

- for any version of xunit newer than vintage 2013:  https://github.com/xunit/xunit.
- for ReSharper:  http://www.jetbrains.com/resharper/?gallery
- for Resharper xUnit test runner: http://resharper-plugins.jetbrains.com/packages/xunitcontrib/

**Comment by jianyunt** [comment]
@nschley thank you for reporting it. I updated the readme.

**Comment by jianyunt** [comment]
Readme is updated.

**Comment by nschley** [comment]
@jianyunt - I tried putting an emoji on your entries, but they're not showing up.  Thanks!
