### ISSUE TITLE
(CP) Install-Package/Uninstall-Package Fails Silently in Remote Session 

### ISSUE THREAD

**Issue by xumins** [OneGet/oneget#24]
https://oneget.codeplex.com/workitem/1

From an interactive remote session calling Install-Package or Uninstall-Package just returns a prompt back. No warning or error to indicate that the package was not successfully installed or uninstalled on the remote endpoint. In addition specifying -Verbose or -Whatif have no effect. 

Image 

 Would be quite cool to have the ability to install and uninstall packages remotely via Remoting.

boeprox wrote Apr 8 at 6:53 PM [x] 
Someone else seemed to have success with using the -Force parameter to install a package and blogged about it:

http://mikefrobbins.com/2014/04/08/using-the-powershell-version-5-preview-oneget-module-with-powershell-remoting/

**Comment by jianyunt** [comment]
it's working now. I tried on the latest oneget on nano server. See errors and warnings are displayed properly.

[10.123.173.173]: PS C:\Users\LocalAdmin\Documents> Find-Package jquery
Find-Package : No match was found for the specified search criteria and package name 'jquery'. Try Get-PackageSource
to see all available registered package sources.
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ets.FindPackage:FindPackage) [Find-Package], Exceptio
   n
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.FindPackage

[10.123.173.173]: PS C:\Users\LocalAdmin\Documents> Get-PackageSource
WARNING: Unable to find package sources.
[10.123.173.173]: PS C:\Users\LocalAdmin\Documents> Register-PackageSource -Name nuget.org -ProviderName nuget -Location
 http://www.nuget.org/api/v2

Name                             ProviderName     IsTrusted  IsRegistered IsValidated  Location
----                             ------------     ---------  ------------ -----------  --------
nuget.org                        NuGet            False      True         True         http://www.nuget.org/api/v2
