### ISSUE TITLE
How to write a provider ?

### ISSUE THREAD

**Issue by lazywinadmin** [OneGet/oneget#241]
Would it be possible to document the process of creating a Provider ?

The MyAlbum module available on the gallery is useful but a proper documentation on how to build a provider step by step should be present in the wiki for example.

cc: @jianyunt

**Comment by jianyunt** [comment]
Hey @lazywinadmin, we will create one. I am tied up with something else right now. It will take sometime. Hope it's ok with you. Thanks for your input.

**Comment by lazywinadmin** [comment]
Thanks @jianyunt ! No problem. It was nice to meet you at the MVP Summit

**Comment by jianyunt** [comment]
@lazywinadmin, please find the [write oneget provider guidelines](https://github.com/OneGet/oneget/blob/master/docs/writepowershellbasedprovider.md). I hope it helps.

**Comment by lazywinadmin** [comment]
Thanks @jianyunt ! This looks great! I will go through it. Closing this Issue and will let you know if I encounter any problem.

**Comment by TSlivede** [comment]
@jianyunt Thanks for writing [writepowershellbasedprovider.md](https://github.com/OneGet/oneget/blob/master/docs/writepowershellbasedprovider.md). 

By now, there is also [ImplementingPackageProvider](https://github.com/OneGet/oneget/wiki/ImplementingPackageProvider).

Both documentations do not link to each other, maybe that should be added?

Which documentation is more up to date?
