### ISSUE TITLE
New-SoftwareIdentityFromXml lacks documentation and examples

### ISSUE THREAD

**Issue by keithga** [OneGet/oneget#250]
I tried creating calling the command manually: 

`New-SoftwareIdentityFromXml -xmlSwidtag '<foo><Version>0.1</Version><Name>MyPackage</Name><Source>c:\foo</Source><VersionScheme>MultiPartNumeric</VersionScheme><Summary>Add the summary of your package provider here</Summary><FastPackageReference>FPR</FastPackageReference></Foo>' -commitImmediately $true`

and it returned an empty object.

**Comment by edyoung** [comment]
That function is not exported by PackageManagement and is an implementation detail, which we wouldn't normally document.
