### ISSUE TITLE
Nuget - Save-Package : Unable to save the package

### ISSUE THREAD

**Issue by mrweiland** [OneGet/oneget#252]
I run this command (below) on our nuget server and some of the packages is failing and i cannot understand why...

> Import-Module -Name PackageManagement
> Save-Package -Name * -Source https://tfs.****.org/tfs/DefaultCollection/_packaging/b7341d25-96e9-4b31-bbd4-a6ae21c60fb9/nuget/v2 -Path C:\temp\nuget.org-copy

```
Save-Package : Unable to save the package '****.Batch.CustomerTransactions.16.10.27.1.nupkg'.
At C:\Temp\PowershellNuget\Untitled2.ps1:5 char:1
+ Save-Package -Name * -Source https://tfs.****org/tfs/DefaultCollec ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power...ets.SavePackage:SavePackage) [Save-Package], Exception
    + FullyQualifiedErrorId : ProviderFailToDownloadFile,Microsoft.PowerShell.PackageManagement.Cmdlets.SavePackage
```

Must be something strange when saving packages in code??

**Comment by brywang-msft** [comment]
I'll take a look when I get a chance, but is there any inner exception data you can provide? Can you also please provide PSGet, PackageManagement, and NuGet.exe versions? Possibly also NuGetProvider version, if you can get it?

**Comment by brywang-msft** [comment]
Hi @mrweiland. This message appears when the download of a package fails for any reason. If you could provide output from ```Save-Package ... -Verbose -Debug```, that would be very helpful. Thank you!

**Comment by jianyunt** [comment]
Hi @mrweiland it will help if you can try with latest PackageManagement version from PowerShell Gallery. Also, please provide the output of "get-packageprovider -ListAvailable"

**Comment by schittli** [comment]
Why is this ticket closed?

Years later, this is still a very common issue that could easily be fixed by providing a useful error description.

It's a shame that this issue was closed but nod fixed. Error messages should be related to the error. Do we have really have to discuss this subject as we did 1/4 century ago?
