### ISSUE TITLE
Similar in function to another DSC resource

### ISSUE THREAD

**Issue by brywang-msft** [OneGet/oneget#258]
_From @JasonMorgan on April 5, 2016 22:27_

I've got a repo here: https://github.com/PowerShellOrg/NuGet that does a lot of similar work.  Any way we can merge these repos together?  I'd be happy to stop maintaining my repo if you could bring in the functionality/classes here.

_Copied from original issue: PowerShell/PackageManagementProviderResource#9_

**Comment by brywang-msft** [comment]
_From @jianyunt on April 6, 2016 17:9_

@JasonMorgan, Thanks for your feedback. 
It's in my backlog to update this project. We may add a generic resource for all the providers.

**Comment by brywang-msft** [comment]
_From @JasonMorgan on April 6, 2016 18:23_

I think you may have meant this response to a different issue.  I opened mine because I have a module that is similar in function to what your module provides.

**Comment by brywang-msft** [comment]
_From @jianyunt on July 20, 2016 17:28_

@JasonMorgan,  I do see some similarity btw these two repo. I think it's good idea to merge. would you mind to do that? We welcome and appreciate contributions from the community. Thanks!

**Comment by jianyunt** [comment]
Merged now.
