### ISSUE TITLE
Chocolatey Package & Source Resources

### ISSUE THREAD

**Issue by brywang-msft** [OneGet/oneget#259]
_From @kilasuit on February 9, 2016 4:31_

I wondered if it would be beneficial to add in DSC resources for Choclatey.

I've been working on them this weekend and if seen as beneficial then I would be happy to submit a PR for it to merge into this repo.

However from my basic testing it seems that package installation works with no issue however I have yet to confirm that package un-installation works without issue. This could be to do with the Chocolatey provider I haven't yet confirmed this.

_Copied from original issue: PowerShell/PackageManagementProviderResource#8_

**Comment by brywang-msft** [comment]
_From @jianyunt on July 20, 2016 17:31_

@kilasuit 

@KrishnaV-MSFT just added a generic DSC resource, which supports "all" providers. The existing OneGet Chocolatey provider is a prototype version. It may not work under various cases.

**Comment by jianyunt** [comment]
The PackageManagement DSC resource is generic so individual provider does not need to their own provider DSC resource now.
