### ISSUE TITLE
Consider checking hashes of packages before installation

### ISSUE THREAD

**Issue by jstangroome** [OneGet/oneget#26]
To help increase trust with inherently untrusted providers, after Install-Package downloads a package locally but before executing/installing the package, a suitable cryptographic hash algorithm should be used to calculate a checksum/digest of the package.

The user can optionally specify the expected checksum as an additional Install-Package parameter and only if the downloaded package's checksum matches the specified checksum would the installation be allow to continue. eg:

    Install-Package -Package dotpeek -Checksum da39a3ee5e6b4b0d3255bfef95601890afd80709

Inevitably it would be useful to introduce a cmdlet that can calculate and display the checksum of a package so that it can be noted and used in future calls to Install-Package.

For providers like Chocolatey, where the package itself is not always self contained and will often download additional payloads from other sources, calculating an overall checksum may be complex. However I'm sure a solution can be found with some investigation and collaboration.

**Comment by jianyunt** [comment]
It's up to the provider implementation. Currently the nuget provider is checking the hash. If hash does not match, we log message.
