### ISSUE TITLE
How to write a Nuget like provider?

### ISSUE THREAD

**Issue by brywang-msft** [OneGet/oneget#261]
_From @dfinke on May 6, 2015 0:3_

I've written a few providers for OneGet. I'm guessing I'd need to follow the Nuget DSC Resource approach to create a DSC Resource for mine?

Thank you

_Copied from original issue: PowerShell/PackageManagementProviderResource#2_

**Comment by brywang-msft** [comment]
_From @KrishnaV-MSFT on July 6, 2016 22:11_

@dfinke is it possible to look at the new generic PackageManagement DSC resource. This will enable using the PackageManagement stuff without writing a new DSC resource (in most cases). I would like to know if this works for you.

**Comment by brywang-msft** [comment]
_From @dfinke on July 6, 2016 22:16_

Let me see what I can do

**Comment by jianyunt** [comment]
For how to write onege provide, see https://github.com/OneGet/oneget/blob/master/docs/writepowershellbasedprovider.md

The PackageManagement DSC resource is generic so individual provider does not need to their own provider DSC now.
