### ISSUE TITLE
Resources are not supposed to have Resource in the module name

### ISSUE THREAD

**Issue by brywang-msft** [OneGet/oneget#262]
_From @TravisEz13 on May 4, 2015 17:57_

_Copied from original issue: PowerShell/PackageManagementProviderResource#1_

**Comment by brywang-msft** [comment]
_From @jianyunt on August 10, 2015 19:22_

Thanks Travis. Do you have a better name for this project?

**Comment by brywang-msft** [comment]
_From @mgreenegit on December 12, 2015 15:9_

PackageManagement

**Comment by brywang-msft** [comment]
_From @jianyunt on December 22, 2015 2:16_

This name is already taken.  PackageManagement (a.k.a OneGet)  is the package manager's aggregator, it's a Windows inbox component and upgrade-able from PowerShellgallery.com. it deals with package discovery and installation etc. 
Here we are dealing with the package provider's DSC resources. So PackageManagement may not be a good name either.

**Comment by brywang-msft** [comment]
_From @gaelcolas on August 26, 2016 16:15_

Just to add an update here, the naming convention is discussed here: https://github.com/PowerShell/PowerShell-RFC/issues/10 and the DSC community calls seems to be leaning towards _ModuleName_Dsc

That would give, IMO, PackageManagementDsc
At least when converted to an HQRM resource.

**Comment by brywang-msft** [comment]
_From @PlagueHO on November 15, 2016 3:39_

My team has been attempting to use this resource and have run into a few bugs that we are fixing. So we are planning on fixing this as well as making the changes to bring it up to HQRM. So once that is done it might be worth renaming this resource at that point.

**Comment by brywang-msft** [comment]
_From @jianyunt on November 15, 2016 17:56_

Can you please send Pull Request for a few bugs you are fixing so that we can integrate them?  
Also we are considering merge this module to the [PackageManagement](https://oneget.org), therefore won't have naming problem.

**Comment by brywang-msft** [comment]
_From @PlagueHO on November 16, 2016 5:25_

Hi @jianyunt - sure thing. I'll get the fixes up to you guys once we figure out a solution - the main problem we have is that registering a package source using DSC registers under the Local System account (I think) rather than for a specific user. This might be a case of running the LCM under a different context (using PSDscRunAsCredential), but that isn't available for WMF4.0.

**Comment by jianyunt** [comment]
Now we merged PackageManagementProviderResource to PackageManagement module.
