### ISSUE TITLE
NuGet.exe finds packages that PackageManagment\Find-Package does not

### ISSUE THREAD

**Issue by dotps1** [OneGet/oneget#270]
Here is the configuration:
I have [SonaType Nexus OSS](https://www.sonatype.com/nexus-repository-oss) hosting my NuGet feed for PowerShell Modules and Scripts.  The Anonymous user only has read rights to root of the nuget repo, this was configured to allow publishing via NuGet and prevent the prompting of credentials which stops PowerShellGet\Publish-Module from working ([LINK](https://support.sonatype.com/hc/en-us/articles/213465068-Why-does-nuget-exe-push-to-Nexus-ask-for-login-credentials-)).  Now, i can publish a module no problem that i have made, it is called `UFPI-Utility`, this module contains helper functions that are used by other modules.  Now, when i try to publish a module that depends on `UFPI-Utility`, it was failing.  And it was failing because when it does it lookup for dependent module, it fails because its not passing the PSCredenital object do the lookup ([I have submitted a Pull Request to PowerShellGet to fix this part](https://github.com/PowerShell/PowerShellGet/pull/93)).
Now, i went to publish a script that requires the top level module which requires `UFPI-Utility`, and it says it fails to find the top level module, which is called `UFPI-SCCM`.  So the order goes like this:
`ControllerScript.ps1 -> Requires UFPI-SCCM Module -> Requires UFPI-Utility Module`

Now, as i dug in, and ran a search using the nuget.exe, it finds the `UFPI-SCCM` module:

```
C:\Users\XXXXXX\AppData\Local\Microsoft\Windows\PowerShell\PowerShellGet> .\NuGet.exe list UFPI -source http://XXXXXX:8081/repository/ufpigallery/
Please provide credentials for: http://XXXXXX:8081/repository/ufpigallery/
UserName: XXXXXX
Password: ***********
UFPI-SCCM 0.1.1
UFPI-Utility 0.1.0
```

However, using `Find-Module` it only finds one module:

```
C:\Users\XXXXXX\AppData\Local\Microsoft\Windows\PowerShell\PowerShellGet> Find-Module -Repository UFPIGallery-Test -Credential (Get-Credential) -Name UFPI*

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
0.1.0      UFPI-Utility                        UFPIGallery-Test     PowerShell Module that contains custom functions...
```

So this totally prevents me from Publishing the script, or even installing the one module.  After going over the PowerShellGet module, it seems like this issue is with the `PackageManagment\Find-Package` cmdlet more so then the `PowerShellGet\Find-Module`

Let me know if there is anymore info i can give, because we would really like to use this in house, but this frankly is a show stopper.

**Comment by jianyunt** [comment]
@dotps1 I noticed that you opened an issue here and send PR to PowerShellGet.  If your PR is merged to PowerShellGet, this issue will be fixed?

**Comment by dotps1** [comment]
No, i do not believe it will.  Hence the last bit of my opening post:

>it seems like this issue is with the PackageManagment\Find-Package cmdlet more so then the PowerShellGet\Find-Module

It doesn't seem to matter or not if i am passing a credential object to Find-Module or not, it does not return both modules, only 1.

**Comment by jianyunt** [comment]
Is your repository based on NuGet V3?  PackageManagement including PSGet currently supports V2 only. For example, find-package Jquery -providerName nuget -source http://www.nuget.org/api/v2.

**Comment by dotps1** [comment]
to be honest, im not sure how to tell.  This is an internal system running SonaType Nexus OSS.  There is a link to the product page in the original post.  I have been looking around the nexus docs, but I don't see anything about the NuGet version.

**Comment by dotps1** [comment]
So, if it is version 3, which i still don't know for sure.  When will package mgmt support v3?  i see the the v4 nuget.exe is already available for testing.

**Comment by brywang-msft** [comment]
Hey, sorry for the late reply. I couldn't find an "official" way of getting the version of your nuget.exe, but you can always right-click -> properties -> details -> file version. I'll create the work item to test support for higher nuget.exe versions, but I can't guarantee its priority.

I'll try to get a repro of this issue so I can investigate more next week most likely. If you think of any information that might help in the meantime, feel free to drop it here. :) Here's what I'll be trying so far:

- Latest PSGet + PackageManagement
- Nexus OSS v3 running in docker
- Publish Module1, Module2 to NuGet repo
- Script.ps1 depends on Module1 depends on Module 2
- Publish Script.ps1

**Comment by dotps1** [comment]
thanks for looking into this.  the version i have in $env:AppData\Microsoft\Windows\PowerShell\PowerShellGet is 2.8.60717.93.

And the only other difference is im not running it in docker.  but i don't think that should matter.

Thanks!

**Comment by jazzdelightsme** [comment]
IMO this bug needs to be prioritized... fresh install of Win10, `Find-Package -Provider Nuget 'NewtonSoft*'` should find a bunch of packages, but finds none.

**Comment by dotps1** [comment]
considering its been about 6 months since the last update, im doubtful.

**Comment by jianyunt** [comment]
Our current PackageManagement NuGet provider supports NuGet protocol V2 only. That’s the reason causing find-package to fail on V3.

I will bring this issue to our team discussion to see if we can prioritize our work to support NuGet protocol V3.

Sorry for the inconvenience.

**Comment by jianyunt** [comment]
@brywang-msft  for the time being,  we can improve our error message to indict V3 NuGet protocol is not supported.

**Comment by dotps1** [comment]
The latest recommended nuget.exe client is 4.1.0 https://www.nuget.org/downloads.  I mean, seems like getting of V2 should defiantly be a priority.

**Comment by Dr-Emann** [comment]
The inability to use modules that depend on other modules via Nexus's NuGet repo is a showstopper for using powershell repositories at my work.

**Comment by Outek** [comment]
Any update on this issue?

**Comment by jianyunt** [comment]
The PackageManagement version https://www.powershellgallery.com/packages/PackageManagement/1.2.0-preview supports V3 already.
You may try it to see if works for you.

install-module PowerShellGet -force -verbose -Repository PSGallery
install-module PackageManagement -force -verbose -AllowPrerelease -Repository PSGallery


``` PowerShell
PS E:\2018> find-package -Provider NuGet -Name NewtonSoft*

Name                           Version          Source           Summary
----                           -------          ------           -------
Newtonsoft.Json                11.0.2           Dan              Json.NET is a popular high-performance JSON framewo...
Newtonsoft.Msgpack             0.1.10           Dan              A library bridging between Newtonsoft.Json and msgp...
Newtonsoft.Json.Encryption     1.3.0            Dan              Package Description
Newtonsoft.Json.Glimpse        1.0.2            Dan              Debug JSON on the server with the Json.NET plugin f...
Newtonsoft.Dson                1.0.3            Dan              DSON (Doge Serialized Object Notation): a data-inte...
Newtonsoft.Json.Legacy         3.5.9            Dan              Json.NET is a popular high-performance JSON framewo...
Newtonsoft.Json.FSharp         3.2.2            Dan              Different serializers for Newtonsoft.Json, making i...
Newtonsoft.JsonResult          1.0.5778.10762   Dan              A JsonResult ActionResult for ASP.NET MVC that uses...
Newtonsoft.Json.Net20.dll      3.5.0            Dan              Newtonsoft.Json.Net20.dll
Newtonsoft.Json.Interface      1.0.4            Dan              The Json.NET Interface Converter/Mapper is a JsonCo...
Newtonsoft.Json.Akshay         5.0.4            Dan              My package description.
Newtonsoft.Json.Bson           1.0.1            Dan              Json.NET BSON adds support for reading and writing ...
Newtonsoft.Json.Schema         3.0.10           Dan              Json.NET Schema is a complete and easy-to-use JSON ...


PS E:\2018> gmo

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Con...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     1.2.0      PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-Pack...
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PS...


PS E:\2018> Get-packageprovider

Name                     Version          DynamicOptions
----                     -------          --------------
msi                      3.0.0.0          AdditionalArguments
msu                      3.0.0.0
NuGet                    3.0.0.1          Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag...
PowerShellGet            1.6.7.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, ...
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent

```

@alerickson is working on some bug fixes for our V3 nuget provider.

cc @edyoung @JKeithB

**Comment by edyoung** [comment]
We're hoping this is resolved by changes above but haven't explicitly validated with Sonatype. Please reactivate if there is still an issue
