### ISSUE TITLE
Can't remove Windows Management Framework 5.0 Production Preview on Windows 7

### ISSUE THREAD

**Issue by fspafford** [OneGet/oneget#276]
I get the error below in the event log. Does anyone have a solution?

Log Name:      Setup
Source:        Microsoft-Windows-WUSA
Date:          4/6/2017 3:38:44 PM
Event ID:      8
Task Category: None
Level:         Error
Keywords:      
User:          HQ\franks
Computer:      MB-SWENG-06...
Description:
Windows update "Windows Management Framework 5.0 Production Preview (KB3066439)" could not be uninstalled because of error 2148204801 "A required certificate is not within its validity period when verifying against the current system clock or the timestamp in the signed file." (Command line: "wusa  /uninstall /kb:3066439 /log")
Event Xml:
```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-WUSA" Guid="{09608C12-C1DA-4104-A6FE-B959CF57560A}" />
    <EventID>8</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2017-04-06T20:38:44.617705600Z" />
    <EventRecordID>3532</EventRecordID>
    <Correlation />
    <Execution ProcessID="9588" ThreadID="10680" />
    <Channel>Setup</Channel>
    <Computer>MB-SWENG-06...</Computer>
    <Security UserID="S-1-5-21-1837231865-1441459807-2961654540-1679" />
  </System>
  <EventData>
    <Data Name="UpdateTitle">"Windows Management Framework 5.0 Production Preview (KB3066439)"</Data>
    <Data Name="ErrorCode">2148204801</Data>
    <Data Name="ErrorString">A required certificate is not within its validity period when verifying against the current system clock or the timestamp in the signed file.</Data>
    <Data Name="CommandLine">wusa  /uninstall /kb:3066439 /log</Data>
  </EventData>
</Event>
```

**Comment by jianyunt** [comment]
This is not a PackageManagement module issue.  I am not sure what a good workaround is apart from changing the system time.
