### ISSUE TITLE
Install-PackageProvider doesn't work on Windows Server Core 10.0.14393.1066

### ISSUE THREAD

**Issue by brywang-msft** [OneGet/oneget#278]
Reported by Mark Gray. Seems to work on 10.0.14393.953. Error mentions not being able to find NuGet.

**Comment by grayzu** [comment]
Adding Docker file where issue was discovered.
[dockerfile.zip](https://github.com/OneGet/oneget/files/965406/dockerfile.zip)

**Comment by edyoung** [comment]
Resolving this seemingly stale issue. If this is a current concern for anyone please reactivate
