### ISSUE TITLE
Unattended Installation of PackageProviders

### ISSUE THREAD

**Issue by kitforbes** [OneGet/oneget#283]
Is it possible to run an unattended installation of package providers? I'd like to use OneGet as part of a Packer build of Windows images.

When I try to install ChocolateyGet as part of a script with
```powershell
Install-PackageProvider -Name ChocolateyGet
```
it prompts for user input. Adding `-ForceBootstrap` or `-Force` (Which I assumed would get around this) did nothing, so not sure what they are for. Add `-Confirm` gets me passed the first prompt, but then you through up an "Are you sure?" prompt...
```powershell
PS C:\WINDOWS\system32> Install-PackageProvider -Name ChocolateyGet -ForceBootstrap -Confirm

Confirm
Are you sure you want to perform this action?
Performing the operation "Install Package" on target "Package 'ChocolateyGet' version '1.0.0.1' from 'PSGallery'.".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):
```

Is there any way to automate this?

**Comment by gaelcolas** [comment]
The main reason is that the Install-PackageProvider is trying to Install a package from an untrusted provider, so it asks you first (it does not seem to pass the $PSBoundParameters to Install-Module/Package).

You can bypass manually by first calling the `Install-module`, then the `Install-PackageProvider`.
```PowerShell
C:\> Install-module chocolateyGet -Force
C:\> Install-PackageProvider -Name ChocolateyGet -Force
```

**Comment by kitforbes** [comment]
Thank you for the answer, @gaelcolas. Consuming PowerShell modules is new to me, so not sure of the best approaches yet.

> Btw, you will also need to install Chocolatey to get `chocolatey.exe` that `ChocolateyGet` leverages.

This is also good to know. I was assuming that this would be self contained.  Having to install `chocolatey.exe` separately makes me wonder what the benefit of OneGet is, in this particular case.

You've solved my issue so I'll happily close this.
