### ISSUE TITLE
Mistakenly removed PowerShellGet module, now can't use MWF cmdlets

### ISSUE THREAD

**Issue by aggieben** [OneGet/oneget#284]
I mistakenly removed the `PowerShellGet` module while monkeying around with package management commands, and now I seem to be pretty stuck.  It appears that installing the PackageManagement modules from the PS Gallery requires already having the modules, and the standalone installers won't work for me because I'm on Windows 10.

How do I fix this?

**Comment by gwojan** [comment]
Copy the modules from a working system and then update from the PowerShell Gallery. I had to do this because I had the old Windows 7 bits on a machine that was upgraded to Windows 10.

**Comment by aggieben** [comment]
@gwojan copy from....$env:ProgramFiles/WindowsPowerShell/Modules?

**Comment by aggieben** [comment]
Ok, that's what I did, and it seems to have resolved the issue.  Thanks!
