### ISSUE TITLE
Trouble installing chocolatey on windows 10

### ISSUE THREAD

**Issue by Deryklink** [OneGet/oneget#288]
This is what comes up when I try to install chocolatey through powershell. Im brand new to computer programming and i cant even get through what should be an easy installation process to even start learning lol. If anyone could help itd be much appreciated. This is what happens when I try to install......

PS C:\WINDOWS\system32> iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
Getting latest version of the Chocolatey package for download.
Getting Chocolatey from https://chocolatey.org/api/v2/package/chocolatey/0.10.5.
Extracting C:\Users\Deryk\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip to C:\Users\Deryk\AppData\Local\Temp\
chocolatey\chocInstall...
Installing chocolatey on this machine
Creating ChocolateyInstall as an environment variable (targeting 'Machine')
  Setting ChocolateyInstall to 'C:\ProgramData\chocolatey'
WARNING: It's very likely you will need to close and reopen your shell
  before you can use choco.
Restricting write permissions to Administrators
We are setting up the Chocolatey package repository.
The packages themselves go to 'C:\ProgramData\chocolatey\lib'
  (i.e. C:\ProgramData\chocolatey\lib\yourPackageName).
A shim file for the command line goes to 'C:\ProgramData\chocolatey\bin'
  and points to an executable in 'C:\ProgramData\chocolatey\lib\yourPackageName'.

Creating Chocolatey folders if they do not already exist.

WARNING: You can safely ignore errors related to missing log files when
  upgrading from a version of Chocolatey less than 0.9.9.
  'Batch file could not be found' is also safe to ignore.
  'The system cannot find the file specified' - also safe.
You cannot call a method on a null-valued expression.
At C:\Users\Deryk\AppData\Local\Temp\chocolatey\chocInstall\tools\chocolateyInstall\helpers\functions\Install-Chocolate
yPath.ps1:80 char:7
+   if (!$envPath.ToLower().Contains($pathToInstall.ToLower()))
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

WARNING: Not setting tab completion: Profile file does not exist at
'C:\Users\Deryk\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'.
Chocolatey (choco.exe) is now ready.
You can call choco from anywhere, command line or powershell by typing choco.
Run choco /? for a list of functions.
You may need to shut down and restart powershell and/or consoles
 first prior to using choco.
Ensuring chocolatey commands are on the path
You cannot call a method on a null-valued expression.
At line:262 char:7
+ if ($($env:Path).ToLower().Contains($($chocoExePath).ToLower()) -eq $ ...
+       ~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Ensuring chocolatey.nupkg is in the lib folder

**Comment by gaelcolas** [comment]
Hi @Deryklink,

This is probably not the place for this question, as Chocolatey is an independent Package Manager (and not directly related to OneGet/PackageManagement).
In short:
- Chocolatey is a Package Manager provided by Chocolatey.org
- OneGet/PackageManagement is a Package **Manager Manager** (a layer on top)

The benefit of Package Management is to have a built-in, common experience across package managers such as NuGet, Msi, Msu, Chocolatey and so on...

I recommend heading to [Chocolatey.org](https://chocolatey.org/faq) to find answers to your question.

That being said, from the logs you posted it seems that your Path environment variable is empty, which is not really normal.
If you fix this (it should at least have C:\WINDOWS\system32 and other things), the install should work.
Things to try to isolate the problem:
- start from a fresh PowerShell session (maybe you've overridden the value of $Env:Path)
- try from another administrative account (maybe the override comes from your $Profile)
- fix your System Path before running the script (if it's empty, it will fail)

Good luck!

**Comment by jianyunt** [comment]
Chocolatey provider is a prototype provider created by OneGet team and is on path for deprecation. Please work with Chocolatey owners to get official support.
