### ISSUE TITLE
Add verification check of location in Add-Packagesource

### ISSUE THREAD

**Issue by proxb** [OneGet/oneget#3]
When using Add-PackageSource, there is no verification of whether the source actually exists. It just adds the source with no questions asked and you won't know until you attempt to find/install a package that the path is not valid. 

```PowerShell
Add-PackageSource -Name Fail -Location 'http://this.willnotwork.com/keeptrying' `
-Provider Chocolatey
```

Even though this is obviously wrong, it is still added and appears in the list of sources when using Get-Packagesource. 

Some sort of checking for either a web location or folder location would help to ensure that the proper package sources are being added to the list of available sources.

Suggest having a confirmation prompt if it cannot successfully validate the location asking to continue adding the source or to exit. Adding a **-Force** parameter would allow this to suppress the prompt and continue adding the package source.

**Comment by jianyunt** [comment]
Fixed.
