### ISSUE TITLE
Remoting from PowerShell 6 to 5.1 is broken

### ISSUE THREAD

**Issue by jianyunt** [OneGet/oneget#304]
User reports:  we need to fix it

Remoting from PowerShell 6 to 5.1 and getting this when I use Install-Module, anyone seen this before?
 
[HOSTNAME]: PS C:\Users\Joey\Documents> Install-Module acmesharp
Object reference not set to an instance of an object.
    + CategoryInfo          : ResourceUnavailable: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException
 

PS C:\Program Files\PowerShell\6.0.0-beta.5> Enter-PSSession localhost
[localhost]: PS C:\Users\manikb\Documents> Get-PackageProvider -verbose -Debug
DEBUG: 00:00:00.0000002 Current running environment: Windows PowerShell.
Object reference not set to an instance of an object.
    + CategoryInfo          : ResourceUnavailable: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException
[localhost]: PS C:\Users\manikb\Documents> Get-PackageProvider -verbose -Debug
Name                     Version          DynamicOptions
----                     -------          --------------
msi                      3.0.0.0          AdditionalArguments
msu                      3.0.0.0
NuGet                    2.8.5.209        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains, AllowPrereleaseVersions, ConfigFile, SkipValidate
PowerShellGet            1.1.3.2          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, InstallUpdate, NoPathUpdate, Filter, Tag, Includes, DscResource, RoleCapability, Command, PublishLocation, ScriptSour...
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent
PSL                      1.0.0.210        Scope, SkipHashValidation, AddToPath, RemoveFromPath

**Comment by joeyaiello** [comment]
Blocked on  PowerShell/PowerShell#4615

**Comment by SteveL-MSFT** [comment]
https://github.com/PowerShell/PowerShell/issues/4615 has been fixed for RC

**Comment by edyoung** [comment]
Works for me
