### ISSUE TITLE
Cant install chocolatey using nuget provider

### ISSUE THREAD

**Issue by idelix** [OneGet/oneget#305]
Hi,
On a server without internet access, I want to install chocolatey.0.10.6.1.nupkg package using nuget provider but the actual package is never installed.

Here are the steps:
1. Create local nuget repo C:\Nuget and copy nuget package chocolatey.0.10.6.1.nupkg
2. Copy nuget provider to the folder C:\Program Files\PackageManagement\ProviderAssemblies\nuget on the server
3. Register nuget repo as source: 
Register-PackageSource -Name "NugetRepo" -Location "C:\Nuget" -ProviderName "NuGet" -Trusted -Verbose
4. Install chocolatey: 
Install-package chocolatey -ProviderName "Nuget" -Source "NugetRepo" -Verbose -Force 

Here is the output:
VERBOSE: Using the provider 'NuGet' for searching packages.
VERBOSE: Total package yield:'1' for the specified package 'chocolatey'.
VERBOSE: Performing the operation "Install Package" on target "Package 'chocolat
ey' version '0.10.6.1' from 'NugetRepo'.".
VERBOSE: InstallPackageLocal' - name='chocolatey', version='0.10.6.1',destinatio
n='C:\Program Files\PackageManagement\NuGet\Packages'

but choco command is not available even after server reboot as well as choco enviornment variables, its like nuget package was never was really installed. I'm executing steps in Windows Server Datacenter 2016 and running powershell ISE as admin as well as using Set-ExecutionPolicy Unrestricted

**Comment by jianyunt** [comment]
PackageManagment/OnGet just download packages, and it does not support for running  package install scripts.
