### ISSUE TITLE
What is Install-Package supposed to do for NuGet packages?

### ISSUE THREAD

**Issue by makhdumi** [OneGet/oneget#325]
Sorry, but I can't find anything in the documentation about this. What's the use case for Install-Package over nuget CLI?

`nuget.exe` already downloads and unpacks NuGet packages. I was hoping that OneGet would load the assemblies, but it appears that it doesn't. Is that right?

**Comment by edyoung** [comment]
Package management is uniform wrapper over multiple different repositories. It doesn't offer much additional functionality (and in some cases offers less) over interacting with the underlying repository directly. The advantage is in having a single tool to deal with multiple kinds of package.
