### ISSUE TITLE
DSC PackageManagement doesn't pass "SourceCredential"

### ISSUE THREAD

**Issue by alexsmid** [OneGet/oneget#345]
## Expected Behavior
Calling PackageManagemt from DSC for installing a module where credentials is needed (in our case, VSTS Package) and the parameter "SourceCredential" should be used.

## Current Behavior
Calling PackageManagement from DSC for installing module "SourceCredential" is not passed correctly to Install-Package -Credential

## Possible Solution
Replace "SourceCredential" parameter with "Credential" or change it in the module

## Steps to Reproduce
Calling Packagemanaget from DSC to install module and passing "SourceCredential"
Error message from DSC log:
*A parameter cannot be found that matches parameter name 'SourceCredential'.*

## Context
We are using PackageManagement to install modules on our DSC for Azure Automation. We have a custom module that is available with NuGet but requires credentials to download.

## Your Environment

```Powershell
>$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.1944
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1944
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by alexsmid** [comment]
@jwittner this seems to have been fixed again in version 1.2.3, can you double check?

**Comment by jwittner** [comment]
@alexsmid - sorry for the almost year delay. I see the change in 1.2.4 (1.2.3 was unlisted), and confirmed it was in 1.4.5 (today's current). I think we can close this bug yeah?

**Comment by alexsmid** [comment]
Yes, i would say so.
