### ISSUE TITLE
Write-S3Object : Method not found

### ISSUE THREAD

**Issue by TypicalTom** [OneGet/oneget#362]
Hi, 

I've had a look around and I don't think this has been raised before, I've also done some searching of the internet to find similar experiences, I have found [this](https://forums.aws.amazon.com/thread.jspa?messageID=805387&tstart=0): and neither of the responses have solved my issue.

I am trying to write an object to an S3 bucket using the following cmdlet:

Write-S3Object -Region "eu-west-1" -BucketName "bucketName" -File "X:\FileName" 

I'm getting the following error:

Write-S3Object : Method not found: 'Void Amazon.S3.Transfer.TransferUtilityUploadRequest.set_TagSet(System.Collections.Generic.List`1<Amazon.S3.Model.Tag>)'.
At O:\ScriptName.ps1:35 char:9
+         Write-S3Object -Region "eu-west-1" -BucketName "bucketname
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-S3Object], MissingMethodException
    + FullyQualifiedErrorId : System.MissingMethodException,Amazon.PowerShell.Cmdlets.S3.WriteS3ObjectCmdlet

I've tried passing a variety of different parameters with the cmd and I've also checked that the powershell module is installed and imported by running cmdlets like:

get-s3bucket | get-s3Object

get-s3bucket | Get-S3BucketLocation

If anyone has any help, it would be greatly appreciated.

Thanks,
Tom.

**Comment by TypicalTom** [comment]
Having re-looked at how I got to this github, I may be posting in the wrong place, apologies if so

**Comment by edyoung** [comment]
Hi Tom - looks to me like this is a problem in the Amazon PowerShell module, not in OneGet, which is just used to install modules. I think you need to report the issue to the owner of that module. Good luck!

**Comment by TypicalTom** [comment]
Hi Ed,

Thanks, I did start to suspect that, I'll re-post now.

Tom
