### ISSUE TITLE
Debugging OneGet Source

### ISSUE THREAD

**Issue by Smorgan05** [OneGet/oneget#366]
How does one go about debugging the **Microsoft.PackageManagement.CoreProviders** in C#.  To be clear I am **not talking about a PS based provider** this is for the C# in OneGet which links up to the registry.  I am specifically talking about this part of OneGet:

* oneget-WIP\src\Microsoft.PackageManagement.CoreProviders\ProgramsProvider.cs

My understanding from looking at the source code in the WIP is that one has to make a console application and then add a reference to PackageManagement and Programs Provider.  Then you likewise do this:

![image](https://user-images.githubusercontent.com/15974943/43042016-4cb3da78-8d3f-11e8-8ffb-78c4ad50b585.png)

Then you can call a method inside the Programs Provider but PackageManagement is an API.  Wherein "An object passed in from the CORE that contains functions that can be used to interact with the CORE and HOST" represents the request.  Now what I want to know is what I have to put in that request field here:

Microsoft.PackageManagement.Internal.Implementation.Request request = ???
provider.GetInstalledPackages("CCleaner", "","","", request);

If this is not possible then we should be able to put the call through PackageManagement to get a similar result.  Thanks!

**Comment by Smorgan05** [comment]
@edyoung is there any chance I could get this answered?

**Comment by jianyunt** [comment]
@Smorgan05, Here is the way I debugged it before:
- git clone this repo
- complile the code https://github.com/oneget/oneget#building-the-code
- using vscode or Visual Studio attach to the powershell process

We should release the pdb files and snap shot the source code for future releases so developers do not need to compile the code again. Sorry @Smorgan05 for the inconvenience.

**Comment by edyoung** [comment]
As Jianyun says, best way to debug c# code loaded into PowerShell is to attach debugger to powershell.exe or launch it as the startup project, then have it run a script to load your module and exercise your cmdlet or other code. Breakpoints in the C# implementation will be hit if symbols are set correctly, and you can single-step through the code as normal.
