### ISSUE TITLE
Fix test issues

### ISSUE THREAD

**Issue by jianyunt** [OneGet/oneget#371]
OneGet checkin and daily test runs are busted. A few issues:
- Test runs are not reported in PR. -- Missing checkin checks.
We need to update the Appveryor site. Currently https://ci.appveyor.com/project/jianyunt/oneget/build/1.0.531/job/m2q688474fqwr3y6

- it reported as pass, actually failed. We need to fix it before we can publish a version of NuGet Provider and PackageManagement.

**Comment by jzabroski** [comment]
Thank you, @jianyunt !!

**Comment by alerickson** [comment]
Resolved #384
