### ISSUE TITLE
install-package can not install software

### ISSUE THREAD

**Issue by lenged** [OneGet/oneget#375]
hi， I have a problem about install-package

when i use install-package vim -Source Chocolatey to install vim8.0 in my pc

but when I type vim in powershell， the error occurs
**### The term 'vim' is not recognized as the name of a cmdlet, function, script file,**

**Comment by edyoung** [comment]
It is possible the path variable was not updated by the chocolatey package for vim. Try opening a new shell window and see if vim works there

**Comment by lenged** [comment]
I try again， but it don‘t work.  I guess it may be powershell can't run install script, because I find the install script in " C:\Chocolatey\bin" , and when I run the install script “ emacsclientw.bat” manally， it can work. 
when I use "get-executionPolicy" the result is “Unrestricted”， please help me fix this error

**Comment by edyoung** [comment]
I don't think emacsclientw.bat has anything to do with vim, they are separate editors.

There are 2 package providers for chocolatey (they are written by the community).

It worked for me by following these steps:

```powershell
Install-PackageProvider ChocolateyGet  # not chocolatey
install-package vim -Source chocolatey
```

You could try "choco search vim' - that might show additional info

**Comment by lenged** [comment]
there is an new error， when I flow your steps to install package， what should I do？
```
WARNING: Unable to download from URI
'https://sourceforge.net/projects/cream/files/Vim/8.0.604/gvim-8-0-604.exe/download' to ''.
install-package : The specified executable is not a valid application for this OS platform.
At line:1 char:1
+ install-package vim -Source chocolatey
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\Lenged...\viminstall.exe:String) [Install-Package], Exception
    + FullyQualifiedErrorId : Process Execution Failed,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

**Comment by edyoung** [comment]
This doesn't seem to be actionable.
