### ISSUE TITLE
Unable to install NuGet

### ISSUE THREAD

**Issue by cmorenoh** [OneGet/oneget#404]
I'm not able to install NuGET in my Windows 2016 DCs with the following error:

PS C:\Users\administrador> Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
Install-PackageProvider : Unable to find repository with SourceLocation ''. Use Get-PSRepository to see all available repositories.
At line:1 char:1
+ Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power...PackageProvider:InstallPackageProvider) [Install-PackageProvider], Exception
    + FullyQualifiedErrorId : RegisterPackageSourceRequired,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackageProvider

I have FIPS disabled, but, anyway, it doesn.t work.

Could you mind to help me, please.

**Comment by alerickson** [comment]
Can you please run `Get-PSRepository`, then run `Get-PackageSource` and share the results?  I think the issue might be that you don't have a Nuget repository registered.

**Comment by cmorenoh** [comment]
Here is the results you asked for:

 

PS C:\Users\administrador> Get-PSRepository

PackageManagement\Get-PackageSource : Unable to find module providers (PowerShellGet).

At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:4458 char:31

+ ... ckageSources = PackageManagement\Get-PackageSource @PSBoundParameters

+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : InvalidArgument: (Microsoft.Power...etPackageSource:GetPackageSource) [Get-PackageSour 

   ce], Exception

    + FullyQualifiedErrorId : UnknownProviders,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPackageSource

 

PS C:\Users\administrador> Get-PackageSource

Get-PackageSource : Unable to find package providers ().

At line:1 char:1

+ Get-PackageSource

+ ~~~~~~~~~~~~~~~~~

    + CategoryInfo          : InvalidArgument: (Microsoft.Power...etPackageSource:GetPackageSource) [Get-PackageSour 

   ce], Exception

    + FullyQualifiedErrorId : UnknownProviders,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPackageSource

 

 

Thank you for your help

 

De: alerickson <notifications@github.com> 
Enviado el: viernes, 23 de noviembre de 2018 23:34
Para: OneGet/oneget <oneget@noreply.github.com>
CC: cmorenoh <cmoreno@infosec.es>; Author <author@noreply.github.com>
Asunto: Re: [OneGet/oneget] Unable to install NuGet (#404)

 

Can you please run Get-PSRepository, then run Get-PackageSource and share the results? I think the issue might be that you don't have a Nuget repository registered.

**Comment by alerickson** [comment]
Can you update to the latest version of [PackageManagement](https://www.powershellgallery.com/packages/PackageManagement/1.2.3) and [PowershellGet](https://www.powershellgallery.com/packages/PowerShellGet/2.0.3) first?

**Comment by cmorenoh** [comment]
I’m no table to install modules you specify, because I’m not able to install NuGet.

 

This is the results when executing both commands:

 

PS C:\Users\administrador> Install-Module -Name PackageManagement

PackageManagement\Install-PackageProvider : Unable to find repository with SourceLocation ''. Use Get-PSRepository to see all available repositories.

At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7405 char:21

+ ...     $null = PackageManagement\Install-PackageProvider -Name $script:N ...

+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : InvalidArgument: (Microsoft.Power...PackageProvider:InstallPackageProvider) [Install-PackageProvider], Exception

    + FullyQualifiedErrorId : RegisterPackageSourceRequired,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackageProvider

PackageManagement\Import-PackageProvider : No match was found for the specified search criteria and provider name 'NuGet'. Try 'Get-PackageProvider -ListAvailable' to see if the 

provider exists on the system.

At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7411 char:21

+ ...     $null = PackageManagement\Import-PackageProvider -Name $script:Nu ...

+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : InvalidData: (NuGet:String) [Import-PackageProvider], Exception

    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.ImportPackageProvider

PackageManagement\Get-PackageProvider : Unable to find package provider 'NuGet'. It may not be imported yet. Try 'Get-PackageProvider -ListAvailable'.

At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7415 char:30

+ ... tProvider = PackageManagement\Get-PackageProvider -Name $script:NuGet ...

+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...PackageProvider:GetPackageProvider) [Get-PackageProvider], Exception

    + FullyQualifiedErrorId : UnknownProviderFromActivatedList,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPackageProvider

Install-Module : NuGet provider is required to interact with NuGet-based repositories. Please ensure that '2.8.5.201' or newer version of NuGet provider is installed.

At line:1 char:1

+ Install-Module -Name PackageManagement

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : InvalidOperation: (:) [Install-Module], InvalidOperationException

    + FullyQualifiedErrorId : CouldNotInstallNuGetProvider,Install-Module

 

 

De: alerickson <notifications@github.com> 
Enviado el: lunes, 26 de noviembre de 2018 0:34
Para: OneGet/oneget <oneget@noreply.github.com>
CC: cmorenoh <cmoreno@infosec.es>; Comment <comment@noreply.github.com>
Asunto: Re: [OneGet/oneget] Unable to install NuGet (#404)

 

Can you update to the latest version of PackageManagement <https://www.powershellgallery.com/packages/PackageManagement/1.2.3>  and PowershellGet <https://www.powershellgallery.com/packages/PowerShellGet/2.0.3>  first?

**Comment by alerickson** [comment]
Try running `Register-PSRepository -default` first to register the PowerShell Gallery.  
And run` gmo packagemanagement -ListAvailable` to see what versions of Package Management you have
