### ISSUE TITLE
My mother tongue is not English. The commands are too long to remember.

### ISSUE THREAD

**Issue by daviddavid97** [OneGet/oneget#418]

**Comment by edyoung** [comment]
Hi, sorry you're having trouble. You could maybe use aliases (see https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_aliases?view=powershell-6) to make shorter names for commands you find difficult to remember.

**Comment by daviddavid97** [comment]
> Hi, sorry you're having trouble. You could maybe use aliases (see https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_aliases?view=powershell-6) to make shorter names for commands you find difficult to remember.

Thank you.
