### ISSUE TITLE
Changelog for 1.3.1

### ISSUE THREAD

**Issue by natescherer** [OneGet/oneget#433]
Unless I'm just missing it, the changes in 1.3.1 aren't listed anywhere? There's not a GitHub release for it, there's no CHANGELOG.md file in the code and the PrivateData ReleaeNotes aren't populated in the psd1. Is there somewhere else changes in releases are communicated?

**Comment by alerickson** [comment]
No, there's been no change log as far as I know, but I'll add one.  Most recent release only has targeting changes-- previous build targets were net451, netcoreapp2.0, and netstandard1.6, it's now just net452 and netstandard2.0
