### ISSUE TITLE
PowerShell SDK 6.1.2 won't install in PSCore 6.1.2 

### ISSUE THREAD

**Issue by MaximoTrinidad** [OneGet/oneget#440]
I'm not sure what I'm missing here. I can find the package but won't install.

I use the send email to Owner but never got a response back. 
:(

# Steps to reproduce
1. Find the package
```powershell
PS [21] > find-package -Name Microsoft.PowerShell.SDK

Name                           Version          Source           Summary
----                           -------          ------           -------
Microsoft.PowerShell.SDK       6.2.0            Nuget            PowerShell runtime for hosting PowerShell Core
```
2. Install the package:
```powershell
PS [27] > Install-Package Microsoft.PowerShell.SDK -RequiredVersion 6.2.0
```
# Expected behavior
To install without any issues
```none

```

# Actual behavior
See cmdline error during installation:
```
PS [33] > 

The package(s) come(s) from a package source that is not marked as trusted.
Are you sure you want to install software from 'Nuget'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
Install-Package : Unable to find dependent package(s) (Microsoft.NETCore)
At line:1 char:2
+  Install-Package Microsoft.PowerShell.SDK -RequiredVersion 6.2.0
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Microsoft.NETCore:String) [Install-Package], Exception
+ FullyQualifiedErrorId : UnableToFindDependencyPackage,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

PS [45] >
```

# Environment data

```none
PS [7] > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS [21] >
```
![PSCoreSDKerr_2019-04-08_18-02-59](https://user-images.githubusercontent.com/19892435/55967159-ce97d080-5c47-11e9-9b21-f73cd17a882e.jpg)

**Comment by SydneyhSmith** [comment]
@MaximoTrinidad  sorry that you are experiencing this issue, and I apologize for the delay in response...this seems like an issue with the package, have you experienced this same/similar issue with other packages using Install-Package?

**Comment by MaximoTrinidad** [comment]
@SydneyhSmith,

Good question! I haven't try.
Let me check and I'll let you know.

:)

**Comment by MaximoTrinidad** [comment]
@SydneyhSmith 

Yes! I can install other package.

![Installpackage_Ok_2019-04-18_19-35-06](https://user-images.githubusercontent.com/19892435/56397318-34202a00-6211-11e9-8f3f-6045cd0a7099.jpg)

**Comment by MaximoTrinidad** [comment]
@SydneyhSmith 

So, it seems that I'm missing all dependencies.  I created a PowerShell Script to install all dependencies that the SDK needs.  

And, of course, discover that some these dependencies has more dependencies.

If I'm successful after all these load then I will close the issue today.

I will post my script in case anyone need to avoid this painful experience!
But, Hey! Never a dull moment!
:)

**Comment by MaximoTrinidad** [comment]
@SydneyhSmith 

No luck!

Too much dependencies to try figure out the proper order of installation. 
I'll wait until .NET Core 3.0 is out and pray that is much simpler to work with it. (Wishful thinking!)

I'm closing the issue!
