### ISSUE TITLE
Wiki Provider-Requests page doesn't mention Linux

### ISSUE THREAD

**Issue by TSlivede** [OneGet/oneget#444]
The [Provider-Requests](https://github.com/OneGet/oneget/wiki/Provider-Requests) page in the Wiki contains the phrase `comprehensive package management in Windows` in the introduction, but does not mention Linux or MacOS (although both are supported according to [readme.md](https://github.com/OneGet/oneget/blob/WIP/readme.md#whats-new) (`supported in Windows, Linux and MacOS now`)).

I'd like to know whether that wiki page should only collect provider requests for Windows or if requests for Linux package managers like `apt-get`, `yum`, `pacman` should be added there as well.

Secondary question: Are only contributors supposed to edit wiki pages or should I just edit that page myself?

**Comment by edyoung** [comment]
feel free to make an edit on the wiki, it should create a PR

**Comment by TSlivede** [comment]
Thanks I've added `apt`, `yum` and `pacman`. It did not create a pull request, the page was updated immediately.
