### ISSUE TITLE
Unable to install NuGet, fails to download from oneget

### ISSUE THREAD

**Issue by KP-GIT** [OneGet/oneget#445]
I am trying to install msonline modules and for that it requires nuget. Now the issue is nuget itself does not gets downloaded. It has something to with the oneget site that is what I think.

I have seen that there is already a similar issue but I could not find any solution here #437 

Want to know what is a workaround as I am pretty new to powershell and stuff.

These are the verbose logs of the command.

PS C:\WINDOWS\system32> Install-Module MSonline -Verbose
VERBOSE: Installing NuGet provider.
VERBOSE: Using the provider 'Bootstrap' for searching packages.
VERBOSE: Finding the package 'Bootstrap::FindPackage' 'NuGet','','2.8.5.201','''.
VERBOSE: Installing the package 'https://onegetcdn.azureedge.net/providers/nuget-2.8.5.208.package.swidtag'.
**WARNING: Unable to download from URI 'https://onegetcdn.azureedge.net/providers/Microsoft.PackageManagement.NuGetProvider-2.8.5.208.dll' to ''.**
**VERBOSE: Cannot download link 'https://onegetcdn.azureedge.net/providers/Microsoft.PackageManagement.NuGetProvider-2.8.5.208.dll', retrying for '2' more times**
.
VERBOSE: Cannot download link 'https://onegetcdn.azureedge.net/providers/Microsoft.PackageManagement.NuGetProvider-2.8.5.208.dll', retrying for '1' more times
.
VERBOSE: Cannot download link 'https://onegetcdn.azureedge.net/providers/Microsoft.PackageManagement.NuGetProvider-2.8.5.208.dll', retrying for '0' more times
.
**PackageManagement\Install-PackageProvider : Failed to bootstrap provider** 'https://onegetcdn.azureedge.net/providers/nuget-2.8.5.208.package.swidtag'.
At C:\Program Files (x86)\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7405 char:21
+ ...     $null = PackageManagement\Install-PackageProvider -Name $script:N ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (https://onegetc...package.swidtag:String) [Install-PackageProvider], Exception
    + FullyQualifiedErrorId : FailedProviderBootstrap,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackageProvider
 
PackageManagement\Import-PackageProvider : No match was found for the specified search criteria and provider name 'NuGet'. Try 'Get-PackageProvider 
-ListAvailable' to see if the provider exists on the system.
At C:\Program Files (x86)\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7411 char:21
+ ...     $null = PackageManagement\Import-PackageProvider -Name $script:Nu ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (NuGet:String) [Import-PackageProvider], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.ImportPackageProvider
 
VERBOSE: No match was found for the specified search criteria and provider name 'NuGet'. Try 'Get-PackageProvider -ListAvailable' to see if the provider exist
s on the system.
VERBOSE: Finding the package 'Bootstrap::FindPackage' 'NuGet','','0.0.0.1','''.
VERBOSE: Installing the package 'https://onegetcdn.azureedge.net/providers/nuget-2.8.5.208.package.swidtag'.
WARNING: Unable to download from URI 'https://onegetcdn.azureedge.net/providers/Microsoft.PackageManagement.NuGetProvider-2.8.5.208.dll' to ''.
VERBOSE: Cannot download link 'https://onegetcdn.azureedge.net/providers/Microsoft.PackageManagement.NuGetProvider-2.8.5.208.dll', retrying for '2' more times
.
VERBOSE: Cannot download link 'https://onegetcdn.azureedge.net/providers/Microsoft.PackageManagement.NuGetProvider-2.8.5.208.dll', retrying for '1' more times
.
VERBOSE: Cannot download link 'https://onegetcdn.azureedge.net/providers/Microsoft.PackageManagement.NuGetProvider-2.8.5.208.dll', retrying for '0' more times
.
PackageManagement\Get-PackageProvider : Failed to bootstrap provider 'https://onegetcdn.azureedge.net/providers/nuget-2.8.5.208.package.swidtag'.
At C:\Program Files (x86)\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7415 char:30
+ ... tProvider = PackageManagement\Get-PackageProvider -Name $script:NuGet ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (https://onegetc...package.swidtag:String) [Get-PackageProvider], Exception
    + FullyQualifiedErrorId : FailedProviderBootstrap,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPackageProvider
 
Install-Module : NuGet provider is required to interact with NuGet-based repositories. Please ensure that '2.8.5.201' or newer version of NuGet provider is 
installed.
At line:1 char:1
+ Install-Module MSonline -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Install-Module], InvalidOperationException
    + FullyQualifiedErrorId : CouldNotInstallNuGetProvider,Install-Module
![Nuget](https://user-images.githubusercontent.com/18345802/56885805-f8942400-6a8a-11e9-8cf5-35c755127a3e.JPG)

**Comment by edyoung** [comment]
Hi, this probably indicates that your company has a proxy server which is denying access to the onegetcdn URL. See https://github.com/OneGet/oneget/issues/439 . You can try:

**Comment by KP-GIT** [comment]
@edyoung Invoking web  request gives a 200 status code. Does that mean everything is setup correctly, only when it is trying to download via the proxy it fails?

**Comment by edyoung** [comment]
Honestly that confuses me a bit. I would expect invoke-webrequest to fail too. What happens if you run invoke-webrequest https://onegetcdn.azureedge.net/providers/Microsoft.PackageManagement.NuGetProvider-2.8.5.208.dll ?

**Comment by KP-GIT** [comment]
When I ran that it threw an error which basically means that it is not able to download the files due to a block at proxy end........I am 100% sure that is the error. So I think because web access is available to that site when I first invoked the request the response is 200. 

But for DLL files there is already a rule applied which restricts their downloading. That is the problem I think. I will check with the team here to bypass that

Thanks a lot for your help!!!!!!! @edyoung

**Comment by zhangkeqiang** [comment]
I also encounter this issue, please give me a clue to resolve this.
My company forbid the download from https://onegetcdn.azureedge.net/providers/Microsoft.PackageManagement.NuGetProvider-2.8.5.208.dll

**Comment by dr-dba** [comment]
**zhang**, try this:
Applications that rely on TLS 1.2 strong encryption experience connectivity failures after a Windows upgrade
https://support.microsoft.com/en-us/help/4458166/applications-that-rely-on-tls-1-2-strong-encryption-experience-connect

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319]
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319]
"SchUseStrongCrypto"=dword:00000001

```
I had the same issue, and was resolved
