### ISSUE TITLE
Move OneGet under Powershell organization, rename PackageManagement

### ISSUE THREAD

**Issue by jzabroski** [OneGet/oneget#468]
@raghushantha  

Thanks for all your contributions to the PackageManagement package.
Please enhance discoverability by placing Oneget under PowerShell umbrella.

As an open source contributor, I have to use Google Search to find that "PackageManagement" is actually hosted as "OneGet" on GitHub.  

I realize you have many priorities as an important member of Azure automation, but remember this:

Simplicity is a force multiplier.  Seek it out, everywhere.

**Comment by SteveL-MSFT** [comment]
For historical reasons, PkgMgmt will stay under OneGet.  OneGet (aka PkgMgmt) is owned by PowerShell Team now).  At present time, I don't have any plans to invest in OneGet.

**Comment by jzabroski** [comment]
@SteveL-MSFT Does that mean new PkgMgmt code will be written in a repository under the GitHub PowerShell organization?  Thank you very much for your reply!
