### ISSUE TITLE
Decouple caching packages from installing packages per-scope

### ISSUE THREAD

**Issue by jzabroski** [OneGet/oneget#469]
1. Align package installation to [ExecutionPolicyScope enum](https://github.com/PowerShell/PowerShell/blob/ceed73d7375cb98a199ceb19796bb2311b0b0002/src/System.Management.Automation/security/SecuritySupport.cs#L73-95)
2. Align package trust to [ExecutionPolicy enum](https://github.com/PowerShell/PowerShell/blob/ceed73d7375cb98a199ceb19796bb2311b0b0002/src/System.Management.Automation/security/SecuritySupport.cs#L31-L65)
3. Replace concept of "trust" and "cache" with unifiying concept of [merkle tree](https://hackernoon.com/merkle-trees-181cb4bc30b4) to separate data from the verification of the data
4. Move [Feature Request: Ability to configure PSRepository on a system-wide level](https://github.com/PowerShell/PowerShellGet/issues/214) located in PowerShell organization's PowerShellGet repository under OneGet issues

**Comment by SydneyhSmith** [comment]
Thanks for the feature request @jzabroski as you know we are currently not investing in PackageMangagement but will consider this as an option for PowerShellGet 3.0...[that RFC](https://github.com/PowerShell/PowerShell-RFC/pull/185) is probably the best place to propose this concept...thanks!

**Comment by jzabroski** [comment]
Closed issue to help cut down on noise in the backlog.  THanks @SydneyhSmith for the heads up!  I actually didn't know PackageManagement was dead.  I'm really not a PowerShell person.
