### ISSUE TITLE
Install-Package does not work if same package is saved in directory.

### ISSUE THREAD

**Issue by xumins** [OneGet/oneget#49]
This is a NuGet provider bug. Repro steps are:

Save-Package -Name Adept.nugetrunner -provider nuget -destination c:\temp
-->
Install-Package -Name Adept.nugetrunner -provider nuget -destination c:\temp
 
 
Install-Package simply executes and does nothing. If you then delete the package you saved in c:\temp and run install, it will actually install it into the directory, so i'm guessing it is having issues installing when something is actually saved there.

**Comment by jianyunt** [comment]
works now.
