### ISSUE TITLE
Install-PackageProvider ignores Force -ForceBootstrap -Confirm:$false, always prompts for confirmation

### ISSUE THREAD

**Issue by abatishchev** [OneGet/oneget#496]
No matter what parameters I pass, e.g.:

```powershell
Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force -ForceBootstrap -Confirm:$false -Verbose
```
It always prompts for confirmation:

```
Would you like PackageManagement to automatically download and install 'nuget' now?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): y
```
What makes impossible to use it fully programmatically. This is a blocking issue for us (Internal Microsoft team) and [the doc](https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/getting-support/bootstrapping-nuget?view=powershell-7) mentions this prompt but says nothing how to skip it.

I opened a separate issue for the doc: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6868

**Comment by SydneyhSmith** [comment]
Thanks @abatishchev what version of PowerShell and what version of PackageManagement are you using?

**Comment by abatishchev** [comment]
Default versions that come with Windows Server 2019 (VMSS in Azure). Then I attempt to install NuGet package provider.

```powershell
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.1490
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1490
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

And `Get-Module -Name PackageManagement` returns nothing. If I understood you correctly; I'm not an epwer in PowerShell packaging ecosystem.

**Comment by abatishchev** [comment]
```powershell
PS > Get-PackageProvider | Select Name,Version

Name          Version
----          -------
msi           3.0.0.0
msu           3.0.0.0
PowerShellGet 1.0.0.1
Programs      3.0.0.0
```

**Comment by SydneyhSmith** [comment]
Thanks @abatishchev try running 
`Get-Module -Name PackageManagement -ListAvailable`

**Comment by abatishchev** [comment]
```powershell
Get-Module -Name PackageManagement -ListAvailable | Select Name,Version

Name              Version
----              -------
PackageManagement 1.0.0.1
```

**Comment by abatishchev** [comment]
My full script looks like this:

```powershell
# Install NuGet
$packageProvider = Get-PackageProvider -Name NuGet -ErrorAction SilentlyContinue
if ($packageProvider)
{
    Write-Output "NuGet package provider $($packageProvider.Version) is already installed"
}
else
{
    Write-Output "Attempting to install NuGet package provider"
    Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -ForceBootstrap -Confirm:$false -Verbose
}
```

and thanks  to @sdwheeler I realized that it's `Get-PackageProvider` that causes the prompt, not `Install-PackageProvider`. How come?

**Comment by abatishchev** [comment]
Also per [the doc](https://docs.microsoft.com/en-us/powershell/module/packagemanagement/unregister-packagesource?view=powershell-7), there is no `Uninstall-PackageProvider`, only `Install-PackageProvider`.

Per the same doc, `Get-PackageProvider`:

>Returns a list of package providers that are connected to Package Management.

It's not supposed to install anything. How come?

**Comment by anamnavi** [comment]
Can you install to the latest version of PackageManagement? (It's version 1.4.7). Just to let you know, Get-PackageProvider is getting the packages/resources which have already been installed via Install-PackageProvider.

**Comment by SydneyhSmith** [comment]
Closing this issue as resolved

**Comment by abatishchev** [comment]
Here's the version of my script that doesn't prompt anymore:

```powershell
# Do not prompt user for confirmations
Set-Variable -Name 'ConfirmPreference' -Value 'None' -Scope Global

# Install PackageManagement
Write-Output "Installing PackageManagement"
Install-Package -Name PackageManagement -MinimumVersion 1.4.7 -Force -Confirm:$false -Source PSGallery

# Install PowershellGet
Write-Output "Installing PowershellGet"
Install-Package -Name PowershellGet -Force -Verbose

# Install Az
$azModule = Get-InstalledModule -Name Az -ErrorAction SilentlyContinue
if ($azModule)
{
    Write-Output "Azure PowerShell module version $($azModule.Version) is already installed"
}
else
{
    Write-Output "Installing Az"
    Install-Module -Name Az -AllowClobber -Scope AllUsers -Force
}

# Install MSAL.PS
$msalPackage = Get-Package -Name MSAL.PS -ErrorAction SilentlyContinue
if ($msalPackage)
{
     Write-Output "MSAL.PS package version $($msalPackage.Version) is already installed"
}
else
{
    Write-Output "Installing MSAL.PS"
    Install-Module -Name MSAL.PS -Force -AcceptLicense -Verbose
}
```

Thanks a lot to @anamnavi and @SydneyhSmith!
