### ISSUE TITLE
Cannot get list of installed software with PowerShell 7

### ISSUE THREAD

**Issue by marco-eckstein** [OneGet/oneget#543]
This is a question, but if the answer is yes (which I am afraid it is), it is also an issue:

In Windows PowerShell (a.k.a. PowerShell 5), one could get a list of installed software with `Get-Package`. In PowerShell (a.k.a. PowerShell Core, PowerShell 7), this is not possible. The list is empty. I guess by adding a package provider like WinGet via `Install-PackageProvider WinGet`, I could get a partial list, but the crucial providers _msi_, _msu_ and _Programs_ are not available, neither built-in nor via `Find-PackageProvider`.

Is Microsoft's modern approach for programmatically getting a list of installed software really using [StackOverflow scripts that access the registry](https://stackoverflow.com/a/73731864/443836)? Or is there a better way?

**Comment by ThomasNieto** [comment]
@marco-eckstein this module is depreciated but you can use its replacement [AnyPackage.Programs](https://www.powershellgallery.com/packages/AnyPackage.Programs) to get the same functionality.

To get started:

```powershell
Install-Module -Name AnyPackage.Programs -Force -AllowClobber
Import-Module AnyPackage.Programs
```

**Comment by marco-eckstein** [comment]
@ThomasNieto Thanks. But apparently, AnyPackage will override all (or most) OneGet commands. I am not sure I want that. What was the motivation for AnyPackage? Why create a new unified package management interface instead of just creating the package providers for OneGet that are missing in PowerShell 7?

**Comment by ThomasNieto** [comment]
@marco-eckstein let me preface by saying I'm not the PowerShell team and have no control over this repository.

The PowerShell team decided to deprecated this module in favor of making a standalone PSResourceGet module replacing PowerShellGet v2 and abandoning the OneGet model. As such the team hasn't made any enhancements or defect corrections. Now that PSResourceGet is stable the stated plan is to remove OneGet and PowerShellGet v2 in the default install of PowerShell. You can still install it using the PSGallery. The only change I would see them making to OneGet and it's providers is if a security vulnerability is found resulting in a patch.

I'm just a community member who likes the OneGet model of provider based interface to various package managers. AnyPackage was created to fix the design limitations of OneGet and simply the implement. These two factors were listed on the PSResourceGet RFC as factors to deprecate OneGet.

AnyPackage is a from the ground up redesign of OneGet and does not share any code but I left the cmdlet names and a majority of the interface similar for users of OneGet.

As for your question on why didn't the PowerShell team just fix the existing providers, it seems as though they just wanted to move on from OneGet.

**Comment by marco-eckstein** [comment]
@ThomasNieto: Thanks for the thorough explanation!

@Other readers for clarification: I had deleted one of my questions in this issue because I had found out some answers on my own shortly afterwards. But @ThomasNieto was very quick and had a reply in the pipeline already.
