### ISSUE TITLE
Install-Package -Update

### ISSUE THREAD

**Issue by Jaykul** [OneGet/oneget#58]
I see that there's no "Update-Package" command, instead there's an -InstallUpdate switch. 

I think the -InstallUpdate switch ought to be just -Update (possibly use an alias for InstallUpdate to maintain compatibility). When I was trying to use the command, I tried `-U{Tab}` looking for an update parameter, but even looking at the syntax blocks I didn't notice the -InstallUpdate parameter until I used search to highlight it  :8ball: 

Additionally I ran these two commands, and then edited the PSCX module manifest to *downgrade* it's version number, and then ran the second command again.

```posh
Install-Package PSCX -Provider PSModule
Install-Package PSCX -Provider PSModule -InstallUpdate -Verbose
```

I was dismayed to find that the version number of the existing version is just never displayed anywhere in the verbose output. That would be nice to fix too.

*P.S.:* Is the behavior of InstallUpdate up to the provider? I assume so.

**Comment by quoctruong** [comment]
Closed since this is related to https://github.com/OneGet/oneget/issues/6
