### ISSUE TITLE
How you retrieve command line values passed in by dynamic options

### ISSUE THREAD

**Issue by dfinke** [OneGet/oneget#76]
I create the dynamic option in `Get-DynamicOptions`
`New-DynamicOption -Category $category -Name "MyUser" -ExpectedType StringArray -isRequired $true`

I guessed to get the value this way, in `Find-Package`
`$MyUser=$request.YieldDynamicOption("MyUser", "StringArray", $true)`

Get this in the console.
`SHOULD NOT GET HERE [YieldSoftwareIdentity] ================================================`

**Comment by jianyunt** [comment]
Here is the example.
   $options = $request.Options
    foreach( $o in $options.Keys )
    {
        Write-Debug ( "OPTION: {0} => {1}" -f ($o, $options[$o]) )
    }
