### ISSUE TITLE
Deal with locale issues

### ISSUE THREAD

**Issue by u9520107** [OneGet/oneget#83]
The installation script seems to try to convert localized time strings to System.DateTime object without success. 

```
Install-Package : Cannot convert value "2014/9/29 下午 11:29:53 +08:00" to type "System.DateTime". Error:
 "The string was not recognized as a valid DateTime. There is an unknown word starting at index 10."
At line:1 char:1
+ Install-Package -name git -Source chocolatey -verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power....InstallPackage:InstallPackage) [Ins
   tall-Package], Exception
    + FullyQualifiedErrorId : InvalidCastParseTargetInvocationWithFormatProvider,New-PSGetItemInfo,Mic
   rosoft.PowerShell.OneGet.CmdLets.InstallPackage
```

**Comment by Uter1007** [comment]
Hi have the same Problem -> is it possible to downgrade the OneGet Version (I used the newest build). Sorry I am a total Powershell N00b. 

Cheers,
Uter

**Comment by Uter1007** [comment]
Changing the Localization works like a charm, I hope to see German localization support in the near future.

**Comment by paulomorgado** [comment]
I'm getting the same error.

Looks like, somewhere, there's code like this:

    [datetime]'18/12/2014 04:22:39 +00:00'

instead of a call to `[DateTime]::ParseExact`.

Any workarounds?

**Comment by ctolkien** [comment]
Seems if `casting` a string to a DateTime, Powershell will always use the USA format, where as the string format of date from .Net depends on the current culture. This line appears to be the culprit:

https://github.com/OneGet/oneget/blob/master/Providers/Inbox/PowerShellGet/PSGet.psm1#L1423

**Comment by ctolkien** [comment]
Here's a further example of this in action (EN-AU locale):

````language-powershell
C:\> [DateTime]"10/1/2015"

Thursday, 1 October 2015 12:00:00 AM

C:\> [DateTime]::Parse("10/1/2015")

Saturday, 10 January 2015 12:00:00 AM
````

**Comment by fearthecowboy** [comment]
Yeah, it's part of the PowerShellGet module, complicated by some overly zealous task cancellation.

It's getting fixed in the next build.

**Comment by doctordns** [comment]
Thanks. But can I ask: next build of what? PowerShell, the cmdlets, Windows 10??

**Comment by fearthecowboy** [comment]
Ah, sorry; was in my own little zone.

For 'Official' builds, we're trying to get to a monthly release cadence, which means the next WMF build should have it (sometime this month), it should also make it's way to the next build of Windows 10 (although, I don't know their release schedule, so I don't know how many weeks away that is).

I'll also try to have it in the OneGet experiemental build in the next day or two (I have to go back and pull the changes from the internal repo and merge them into my external tree).

G

**Comment by ctolkien** [comment]
If you can figure out the appropriate file permissions (I couldn't!), you should be able to update this file yourself in your own Win10 build to at least get PowerShellGet to work.

**Comment by fearthecowboy** [comment]
You're not going to be able to overwrite the one that's built in; the SFC stuff in Windows will go to the ends of the earth to stop you from changing those files ;)

**Comment by jianyunt** [comment]
I tried to repro this on the latest WMF 5.0 or the Windows Server 2016 Technical Preview. This problem has been fixed. No repro anymore.
