### ISSUE TITLE
OneGet Import fails to load in Powershell for Windows 7 SP1

### ISSUE THREAD

**Issue by onepremise** [OneGet/oneget#87]
Hi Guys,

I was trying to test your latest [download](http://oneget.org/oneget.zip) and haven't had much luck importing into powershell. When I follow instructions/readme, I encounter the following exception:

```
PS D:\projects\tools\oneget> .\RunToUnBlock.cmd
PS D:\projects\tools\oneget> ipmo .\OneGet.psd1
Import-Module : The 'D:\projects\tools\oneget\OneGet.psd1' module cannot be imported because its manifest contains one
or more members that are not valid. The valid manifest members are ('ModuleToProcess', 'NestedModules', 'GUID', 'Author
', 'CompanyName', 'Copyright', 'ModuleVersion', 'Description', 'PowerShellVersion', 'PowerShellHostName', 'PowerShellHo
stVersion', 'CLRVersion', 'DotNetFrameworkVersion', 'ProcessorArchitecture', 'RequiredModules', 'TypesToProcess', 'Form
atsToProcess', 'ScriptsToProcess', 'PrivateData', 'RequiredAssemblies', 'ModuleList', 'FileList', 'FunctionsToExport',
'VariablesToExport', 'AliasesToExport', 'CmdletsToExport'). Remove the members that are not valid ('HelpInfoUri', 'Root
Module'), then try to import the module again.
At line:1 char:5
+ ipmo <<<<  .\OneGet.psd1
    + CategoryInfo          : InvalidData: (D:\projects\tools\oneget\OneGet.psd1:String) [Import-Module], InvalidOpera
   tionException
    + FullyQualifiedErrorId : Modules_InvalidManifestMember,Microsoft.PowerShell.Commands.ImportModuleCommand
```

Maybe there's an undocumented step missing? Any help greatly appreciated. THanks.

**Comment by fearthecowboy** [comment]
Mental Note: See if there is a way to warn a PowerShell 2.0 user that this won't install.

**Comment by robmen** [comment]
The install package does this, IIRC (and could if it doesn't) if you accept the pull request. :)
________________________________

**Comment by fearthecowboy** [comment]
@robmen Indeed-> I will pull that in this week.

**Comment by S3curityPlu5** [comment]
Go to windows 8,1, windows 7 lacks so many enterprise features and there is so many reasons to move to 8.1, i really haven't seen more than one app that I couldn't migrate to 8.1.  The benefits far outweigh the disadvantages, sorry if I sound like i work for microsoft but I don't.  I have moved all my customers from windows 7, and there have been few complaints. I have a feeling that everyone will upgrade once 10 is released, why wait>?
