### ISSUE TITLE
NuGetProvider submodule invalid reference.

### ISSUE THREAD

**Issue by firegiantco** [OneGet/oneget#91]
The NuGetProvider @ 780c235 does not exist. Maybe the NuGetProvider repository was force pushed since it only seems to contain a single commit?

The lack of NuGetProvider breaks the build.

**Comment by fearthecowboy** [comment]
hmm. gimme a sec.

**Comment by fearthecowboy** [comment]
ok, I've pushed my wip branch again along with the latest nugetprovider

**Comment by jianyunt** [comment]
Please use the latest version of nuget provider 2.8.5.201
